(()=>{
'use strict';const R=window.MobArenaRules,core=window.MobPartyCore,SAVE='mob-game-king-arena-v1';
window.MobGameKingArena={create(host){const {screen,esc}=host;let state=null,token=0,humans=[],mode='solo40',jobs=new Set(),motion=null;
const title=key=>host.title(key),team=id=>state.teams.find(t=>t.id===id),player=id=>state.players.find(p=>p.id===id),picture=p=>`<img draggable="false" src="${p.img}" alt="${esc(p.name)}">`;
function save(){try{localStorage.setItem(SAVE,JSON.stringify(state));}catch{screen.querySelector('.arena-save-status')?.replaceChildren(document.createTextNode('この端末では途中保存できません。'))}}
function stored(){try{return R.restore(JSON.parse(localStorage.getItem(SAVE)))}catch{return null}}
function stop(){token++;jobs.forEach(clearTimeout);jobs.clear();motion?.cancel();motion=null;state=null}
function later(fn,ms){const own=token,id=setTimeout(()=>{jobs.delete(id);if(own===token)fn()},ms);jobs.add(id)}
function draw(heading,body,kind=''){host.clear();screen.innerHTML=`<section class="arena ${kind}"><header><small>MOB GAME KING · ${state?R.MODES.find(m=>m.id===state.mode).label:'CHAMPIONS ARE MADE HERE'}</small><h1>${heading}</h1></header>${body}<small class="arena-save-status" role="status"></small></section>`;host.top();const el=screen.querySelector('.arena');el.style.setProperty('--arena-top',Math.max(0,el.getBoundingClientRect().top)+'px')}
function on(id,fn){const el=screen.querySelector('#'+id);let used=false;el.onclick=()=>{if(used)return;used=true;el.disabled=true;if(fn()===false){used=false;el.disabled=false}}}
function setup(){stop();draw('モブくんはゲーム王',`<div class="arena-emblem">MOB<small>ROAD TO THE CROWN</small></div><p>50ptで点灯。その次の回以降に1位を取れば優勝！</p><label>モード<select id="arenaMode">${R.MODES.map(m=>`<option value="${m.id}">${m.label} · ${m.size*m.teams}名</option>`).join('')}</select></label><label>人間プレイヤー<select id="arenaHumans">${Array.from({length:9},(_,n)=>`<option value="${n}" ${n===1?'selected':''}>${n}人${n===0?' · CPU観戦':''}</option>`).join('')}</select></label><details><summary>得点・代表・同点のルール</summary><p>順位はプレイした選手の素点合計。同率は同順位、次順位は人数分飛びます。1〜8位：12 / 8 / 6 / 5 / 4 / 3 / 2 / 1pt。</p><p>各選手のボーナス：40点＋1、50点＋2、60点＋3、70点＋4、80点＋5、90点＋7、100点＋10。最高該当のみ。タッグは全員→全員→代表1名、Crewは全員→代表2名→代表1名。</p><p>点灯済みの同率1位が複数なら、そのチームだけ延長戦。延長戦の得点は累計に加算せず、単独1位で優勝。手動の説明・準備時間を除き15秒未満と確認した${R.ALLOWED.length}種目から毎回5候補を抽選。</p></details><button id="arenaEnter" class="primary">キャラクターを決める</button>${stored()?'<button id="arenaResume">保存した大会を再開</button>':''}`,'arena-setup');on('arenaEnter',()=>{mode=screen.querySelector('#arenaMode').value;const count=Number(screen.querySelector('#arenaHumans').value);humans=[];chooseHuman(0,count)});if(stored())on('arenaResume',()=>{state=stored();if(!state)return setup();host.configure(state.players,state.teams,{mode:'arena',title:'モブくんはゲーム王'});resume()})}
function chooseHuman(index,count){if(index===count){assign();return}window.MobCharacterSelect.show({screen,esc,count,index,slots:humans.map(p=>p.characterId),top:host.top,beep:host.beep,back:setup,confirm(c){if(humans.some(p=>p.characterId===c.id))return;humans.push({...c,characterId:c.id,id:'arenaP'+index,no:index+1,cpu:false,characterRank:c.rank});chooseHuman(index+1,count)}})}
function assign(){const spec=R.MODES.find(m=>m.id===mode);if(!humans.length){begin([]);return}draw('参加チームを決めよう',`<div class="arena-assign">${humans.map((p,i)=>`<label>${picture(p)}<span>P${i+1} ${esc(p.name)}</span><select data-arena-team="${i}">${Array.from({length:spec.teams},(_,n)=>`<option value="${n}" ${n===Math.floor(i/spec.size)?'selected':''}>${spec.size===1?'出場枠':'TEAM'} ${n+1}</option>`).join('')}</select></label>`).join('')}</div><p id="arenaError" role="alert"></p><button id="arenaBegin" class="primary">大会スタート</button>`);on('arenaBegin',()=>{const groups=[...screen.querySelectorAll('[data-arena-team]')].map(el=>Number(el.value));if(groups.some(n=>groups.filter(x=>x===n).length>spec.size)){screen.querySelector('#arenaError').textContent=`1チーム${spec.size}人までです。`;return false}begin(groups)})}
function begin(groups){const spec=R.MODES.find(m=>m.id===mode),teams=Array.from({length:spec.teams},(_,i)=>({id:'A'+i,name:'TEAM '+(i+1),members:[]})),players=[...humans];humans.forEach((p,i)=>teams[groups[i]].members.push(p.id));const candidates=R.sample(core.roster.filter(c=>!humans.some(p=>p.characterId===c.id)),spec.size*spec.teams-humans.length);let n=0;for(const t of teams)while(t.members.length<spec.size){const c=candidates[n];if(!c)throw Error('Not enough distinct characters');const p={...c,characterId:c.id,id:'arenaCPU'+n,no:humans.length+n+1,cpu:true,characterRank:c.rank};players.push(p);t.members.push(p.id);n++}if(spec.size===1)teams.forEach(t=>t.name=players.find(p=>p.id===t.members[0]).name);state=R.create(mode,teams,players);host.configure(players,teams,{mode:'arena',title:'モブくんはゲーム王'});state.phase='opening';save();opening()}
function resume(){if(state.phase==='opening')return opening();if(state.champion)return champion();if(state.last&&state.phase==='result')return results();if(state.pending?.revealed)return representatives();roulette()}
function opening(){
 draw('モブくんはゲーム王',`<div class="arena-opening-stage"><div class="arena-opening-rays"></div><div class="arena-crown" aria-hidden="true">♛</div><strong class="arena-opening-title">GAME KING</strong><p class="arena-opening-mode">${R.MODES.find(m=>m.id===state.mode).label}</p><div class="arena-opening-rules"><div><b>01</b><strong>勝負を重ねる</strong><span>順位ポイント ＋ 各選手のボーナス</span></div><div><b>50</b><strong>累計50ptで点灯</strong><span>王者への挑戦権を獲得</span></div><div><b>♛</b><strong>点灯した次の回から</strong><span>1位を取れば、ゲーム王！</span></div></div></div><button id="arenaOpeningGo" class="primary">王座を目指す · ルーレットへ</button>`,'arena-opening');
 host.beep(440,100,.02);later(()=>host.beep(660,100,.02),850);later(()=>host.beep(990,160,.03),1700);on('arenaOpeningGo',roulette);
}
function roulette(){const p=R.prepare(state),leaders=[...state.teams].sort((a,b)=>state.totals[b.id]-state.totals[a.id]),gap=state.totals[leaders[0].id]-state.totals[leaders[1].id],race=state.round?(gap?'首位と2位、'+gap+'pt差！':'首位が並ぶ、次が勝負！'):'';state.phase='draw';save();draw(`${p.overtime?'優勝決定・延長戦':'ROUND '+p.id}`,`<p class="arena-round-note">${p.count===R.MODES.find(m=>m.id===state.mode).size?'全員出場':`各チーム代表${p.count}名`} · ${state.lit.length?'点灯 '+state.lit.length+'組 / 勝てば王者':'50ptへのレース'} ${race}</p><div class="arena-wheel-stage"><div class="arena-rays"></div><i class="arena-pointer">▼</i><div id="arenaWheel" class="arena-wheel">${p.choices.map((k,i)=>`<span style="--i:${i}">${i+1}</span>`).join('')}<b>MOB<br>ROULETTE</b></div></div><ol class="arena-candidates">${p.choices.map((key,i)=>`<li data-arena-candidate="${key}"><b>${i+1}</b>${esc(title(key))}</li>`).join('')}</ol><p id="arenaDrawCall" aria-live="polite">5つの舞台、運命の1ゲーム。</p><button id="arenaSpin" class="primary">ルーレットを回す</button>`,'arena-draw');on('arenaSpin',()=>{const own=token,wheel=screen.querySelector('#arenaWheel'),rotation=1800-p.choices.indexOf(p.key)*72-36;host.beep(620,130,.025);const reveal=()=>{if(token!==own||!state)return;wheel.style.transform=`rotate(${rotation}deg)`;screen.querySelector(`[data-arena-candidate="${p.key}"]`).classList.add('selected');screen.querySelector('#arenaDrawCall').textContent='決定！ '+title(p.key);p.revealed=true;save();const button=screen.querySelector('#arenaSpin');button.disabled=false;button.textContent='このゲームに進む →';on('arenaSpin',representatives);host.beep(1100,190,.03)};motion=wheel.animate?.([{transform:'rotate(0)'},{transform:`rotate(${rotation}deg)`}],{duration:matchMedia('(prefers-reduced-motion: reduce)').matches?100:1900,easing:'cubic-bezier(.08,.65,.15,1)',fill:'forwards'});if(motion)motion.finished.then(reveal,()=>{});else reveal()})}
function representatives(){const p=state.pending;for(const id of p.active){const t=team(id);if(p.representatives[id])continue;if(p.count===t.members.length){p.representatives[id]=[...t.members];continue}if(t.members.every(id=>player(id).cpu)){p.representatives[id]=R.sample(t.members,p.count);continue}let selected=[];draw(`代表${p.count}名を選ぼう`, `<p>${esc(t.name)} · ${esc(title(p.key))}</p><div class="arena-representatives">${t.members.map((id,i)=>`<button data-arena-rep="${id}" aria-pressed="false">${picture(player(id))}<b>${esc(player(id).name)}</b><small>${player(id).cpu?'CPU':'P'+player(id).no}</small></button>`).join('')}</div><p id="arenaRepCount">0 / ${p.count}名</p><button id="arenaRepConfirm" class="primary" disabled>この代表で挑戦</button>`);screen.querySelectorAll('[data-arena-rep]').forEach(b=>b.onclick=()=>{const id=b.dataset.arenaRep;if(selected.includes(id))selected=selected.filter(v=>v!==id);else if(selected.length<p.count)selected.push(id);screen.querySelectorAll('[data-arena-rep]').forEach(el=>el.setAttribute('aria-pressed',String(selected.includes(el.dataset.arenaRep))));screen.querySelector('#arenaRepCount').textContent=selected.length+' / '+p.count+'名';screen.querySelector('#arenaRepConfirm').disabled=selected.length!==p.count});on('arenaRepConfirm',()=>{p.representatives[t.id]=selected;save();representatives()});return}state.phase='play';save();runNext()}
function runNext(){const p=state.pending,id=p.active.find(id=>!p.completed.includes(id));if(!id){R.submit(state,p.id,p.points);save();return state.champion?champion():results(true)}const t=team(id),own=token,entrants={...t,members:p.representatives[id]};draw('挑戦中',`<div class="arena-playing">${entrants.members.map(id=>picture(player(id))).join('')}<h2>${esc(t.name)}</h2><p>${esc(title(p.key))}</p><small>${p.completed.length+1} / ${p.active.length}組</small></div>`);host.run(p.key,[entrants],{phase:'arena',round:p.id},scores=>{if(token!==own||!state||state.pending!==p||p.completed.includes(id))return;for(const member of entrants.members){const v=scores[member];if(!Number.isFinite(v)||v<0||v>100)throw Error('Invalid game score');p.points[member]=v}p.completed.push(id);save();runNext()})}
function results(announce=false){const result=state.last;if(announce&&result.newlyLit.length){draw('MATCH POINT · 点灯！',`<div class="arena-ignition">50<small>POINTS</small></div><h2>次の1位で、ゲーム王！</h2><p>${result.newlyLit.length}組が点灯しました。</p><p>${result.newlyLit.slice(0,4).map(id=>esc(team(id).name)).join(' ／ ')}${result.newlyLit.length>4?' ほか':''}</p><button id="arenaLitNext" class="primary">リザルトを見る</button>`,'arena-lit');host.beep(1200,200,.035);on('arenaLitNext',()=>results());return}let view='round';const render=()=>{
 const rows=view==='round'?[...result.rows]:state.teams.map(t=>result.rows.find(r=>r.id===t.id)||{id:t.id,rank:null,rankPoints:0,members:[],earned:0,total:state.totals[t.id]}).sort((a,b)=>b.total-a.total);
 draw(view==='round'?'ROUND RESULTS':'OVERALL STANDINGS',`<nav class="arena-result-tabs"><button id="arenaRoundTab" aria-pressed="${view==='round'}">今回の順位</button><button id="arenaTotalTab" aria-pressed="${view==='total'}">総合順位</button></nav><p class="arena-result-caption">ROUND ${result.id} · ${esc(title(result.key))}<br>全${rows.length}組 · 一覧を上下にスクロール${result.overtime?' · 延長戦は累計加算なし':''}${result.tiedContenders?' · 同点のため優勝決定戦へ':''}</p><div class="arena-score-list" tabindex="0" aria-label="全チームの順位と得点">${rows.map(r=>{
 const overall=1+state.teams.filter(t=>state.totals[t.id]>r.total).length,rank=view==='round'?r.rank:overall;
 return `<article class="arena-scorecard ${state.lit.includes(r.id)?'lit':''}"><header><span class="arena-rank">#${rank||'—'}</span><b>${esc(team(r.id).name)}</b><em>${state.lit.includes(r.id)?'● 点灯':'50ptで点灯'}</em></header><p class="arena-rank-pair">今回 #${r.rank||'—'}<span>総合 #${overall}</span></p><div class="arena-score-main"><span>順位ポイント<strong>${r.rankPoints}<small>pt</small></strong></span><span>今回獲得合計<strong>+${r.earned}<small>pt</small></strong></span><span>累計<strong>${r.total}<small>pt</small></strong></span></div><div class="arena-score-members">${team(r.id).members.map(id=>{const m=r.members.find(m=>m.id===id);return `<div>${picture(player(id))}<span>${esc(player(id).name)}<small>${m?'素点 '+m.raw+' · ボーナス +'+m.bonus+'pt':'今回出場なし · 加点なし'}</small></span></div>`}).join('')}</div><footer>${r.rank?'素点合計 '+r.base+' · 順位 '+r.rankPoints+' ＋ ボーナス '+r.bonus+' ＝ '+(result.overtime?'0（延長）':r.earned)+'pt':'今回の延長戦は不参加'}</footer></article>`}).join('')}</div><button id="arenaNextRound" class="primary">${state.champion?'優勝画面へ':result.tiedContenders?'優勝決定戦へ':'次のルーレットへ'} →</button>`,'arena-results');
 on('arenaRoundTab',()=>{view='round';render()});on('arenaTotalTab',()=>{view='total';render()});on('arenaNextRound',()=>state.champion?champion():roulette());};render()}

function champion(){state.phase='champion';save();const winner=team(state.champion);draw('CHAMPION!',`<div class="arena-celebration"><div class="arena-fireworks" aria-hidden="true">${Array.from({length:18},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div><div class="arena-champ-portraits">${winner.members.map(id=>picture(player(id))).join('')}</div><h2>${esc(winner.name)}</h2><p>モブくんはゲーム王</p><strong>${state.totals[winner.id]}pt · ${state.round} ROUNDS</strong></div><button id="arenaWallpaper" class="primary">優勝壁紙を作る</button><button id="arenaChampionResult">決着の結果を見る</button><button id="arenaFinish">メインへ戻る</button>`,'arena-champion');host.beep(1350,350,.04);on('arenaWallpaper',()=>window.MobChampionStudio.open({screen,esc,members:winner.members.map(player),teamName:winner.name,competition:'モブくんはゲーム王',done:champion}));on('arenaChampionResult',()=>championResults());on('arenaFinish',host.home)}
function championResults(){results();const b=screen.querySelector('#arenaNextRound');b.textContent='優勝画面へ →';on('arenaNextRound',champion)}
return{setup,stop,active:()=>!!state&&!state.champion};
}};
})();
