(function(root){
  'use strict';
  const games=['reaction','monsterBoxMob','longJumpMob','brake','mobIssen'];
  const rank=score=>score>=480?'MOB':score>=450?'UR':score>=400?'SSR':score>=320?'SR':'R';
  const top20=rows=>rows.filter(r=>r&&Number.isFinite(r.total)&&r.total>=0&&r.total<=500&&typeof r.playerName==='string').sort((a,b)=>b.total-a.total||b.perfect-a.perfect||a.stamp-b.stamp).slice(0,20);
  const api={games,rank,top20};if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(!root)return;
  root.MobGameKing={...api,create(host){
    const {screen,esc}=host;let token=0,entry=null,history=[],round=0,scores=[];
    const key='mob-game-king-records-v1';
    function draw(title,body){host.clear();screen.innerHTML=`<section class="king-page"><header><small>MOB GAME KING CHALLENGE</small><h1>${title}</h1></header>${body}</section>`;host.top();}
    function on(id,fn){const b=screen.querySelector('#'+id);let used=false;b.onclick=()=>{if(used)return;used=true;b.disabled=true;fn();};}
    function stop(){token++;}
    function setup(){stop();draw('MOB GAME KING',`<div class="king-opening">♛<p>5つの試練。目指せ、500点の頂点。</p></div><button id="kingNext" class="primary">挑戦のルールを見る</button><button id="kingHome" class="secondary">メインへ戻る</button>`);on('kingNext',rules);on('kingHome',host.home);}
    function rules(){draw('5 GAMES · 500 POINTS',`<ol>${games.map(k=>`<li>${esc(host.title(k))}</li>`).join('')}</ol><p>各ゲーム100点、合計500点。満点回数もカードに刻まれます。</p><div class="king-ranks">480–500 MOB ／ 450–479 UR<br>400–449 SSR ／ 320–399 SR ／ 0–319 R</div><p>歴代TOP20はこの端末のブラウザーに保存。同点は満点回数、同数なら先に達成した記録が上位です。</p><button id="kingNext" class="primary">名前とキャラクターを選ぶ</button>`);on('kingNext',select);}
    function select(){const roster=root.MobPartyCore.roster;draw('挑戦者を登録',`<label>プレイヤー名<input id="kingName" maxlength="20" placeholder="名前を入力" autocomplete="nickname"></label><div class="king-roster">${roster.map(c=>`<button data-king-char="${c.id}" aria-pressed="false"><img src="${c.img}" alt="${esc(c.name)}"><small>${esc(c.name)}</small></button>`).join('')}</div><p id="kingError" role="alert"></p><button id="kingConfirm" class="primary" disabled>キャラクターを選んで決定</button>`);let chosen=null;const button=screen.querySelector('#kingConfirm');screen.querySelectorAll('[data-king-char]').forEach(b=>b.onclick=()=>{chosen=roster.find(c=>c.id===Number(b.dataset.kingChar));screen.querySelectorAll('[data-king-char]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));button.disabled=false;button.textContent=chosen.name+'で挑戦';});button.onclick=()=>{const name=screen.querySelector('#kingName').value.trim();if(!name){screen.querySelector('#kingError').textContent='プレイヤー名を入力してください。';return;}entry={playerName:name,characterName:chosen.name,img:chosen.img,characterId:chosen.id,date:root.MobCollectibles.date()};leaderboard();};}
    function read(){try{return top20(JSON.parse(localStorage.getItem(key)||'[]'));}catch(_){return [];}}
    function leaderboard(){history=read();draw('歴代 TOP 20',`<p>${esc(entry.playerName)}さん、記録に名を刻もう！</p><div class="king-podium">${history.slice(0,3).map((r,i)=>`<article><b>${i+1}位</b><canvas data-king-card="${i}" role="img"></canvas></article>`).join('')}</div>${history.slice(3).map((r,i)=>`<p class="king-history-row">${i+4}位　${esc(r.playerName)}　<strong>${r.total}点 / ${esc(r.rank)}</strong><small>${esc(r.characterName)} · ${esc(r.date)} · 満点${r.perfect}回</small></p>`).join('')}${history.length?'':'<p>まだ記録はありません。最初の挑戦者になろう！</p>'}<button id="kingStart" class="primary">チャレンジスタート</button>`);screen.querySelectorAll('[data-king-card]').forEach(c=>root.MobCollectibles.card(c,history[Number(c.dataset.kingCard)]));on('kingStart',()=>{scores=[];round=0;host.configure(entry);next();});}
    function next(){if(round===5){finish();return;}draw(`GAME ${round+1} / 5`, `<h2 class="king-next-title">${esc(host.title(games[round]))}</h2><p>現在 ${scores.reduce((a,b)=>a+b,0)} / ${round*100}点。${round===4?'いよいよ最後の試練！ 三連の一閃で記録を刻め！':'次の試練が始まる。落ち着いて、最高の一回を！'}</p><button id="kingNext" class="primary">このゲームに挑戦</button>`);on('kingNext',()=>{const own=token;host.run(games[round],round,score=>{if(own!==token)return;scores.push(Math.max(0,Math.min(100,Math.round(score))));round++;next();});});}
    function finish(){const total=scores.reduce((a,b)=>a+b,0);entry={...entry,total,rank:rank(total),perfect:scores.filter(v=>v===100).length,stamp:Date.now(),scores:[...scores]};const updated=top20([...read(),entry]),position=updated.indexOf(entry);let saved=false;if(position>=0)try{localStorage.setItem(key,JSON.stringify(updated));saved=true;}catch(_){}
      draw('CHALLENGE COMPLETE',`<div class="king-final-score">${total}<small>/ 500</small></div><div class="king-rank-reveal">RANK ${entry.rank}</div><ol>${games.map((g,i)=>`<li>${esc(host.title(g))}<b>${scores[i]}pt</b></li>`).join('')}</ol><p>${position>=0?saved?`歴代 ${position+1}位！ 記録を保存しました。`:'TOP20入り！ このブラウザーでは記録を保存できませんでした。':'TOP20まであと一歩。カードには今回の挑戦を残せます。'}</p><button id="kingNext" class="primary">記念トレカを制作する</button>`);host.beep(1250,200,.03);on('kingNext',cardResult);
    }
    async function cardResult(){draw('YOUR KING CARD',`<canvas id="kingCard" class="king-card" role="img"></canvas><button id="kingSave" class="primary" disabled>画像を保存する</button><p id="kingSaveState" role="status">カードを制作中…</p><button id="kingEnd" class="secondary">ゲームを終わる</button>`);const canvas=screen.querySelector('#kingCard'),save=screen.querySelector('#kingSave');on('kingEnd',()=>{stop();host.home();});await root.MobCollectibles.card(canvas,entry);if(!canvas.isConnected)return;save.disabled=false;screen.querySelector('#kingSaveState').textContent='白背景のPNG画像として保存できます。';save.onclick=()=>root.MobCollectibles.save(canvas,'MOB-GAME-KING-'+entry.rank);}
    return {setup,stop};
  }};
})(typeof window==='undefined'?null:window);
