const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict'),{chromium}=require('playwright');
const inRepo=path.basename(__dirname)==='tests',root=inRepo?path.resolve(__dirname,'..'):'C:/Users/user/Documents/GitHub/MOB-mini-game',dir=inRepo?fs.mkdtempSync(path.join(require('os').tmpdir(),'mob-approved-native-')):__dirname,actual=inRepo||process.argv.includes('--actual'),old=false;const report={actual,old,checks:[],errors:[]};
const server=http.createServer((req,res)=>{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname).slice(1)||'index.html';const local=['index.html','game.js','party-approved-games.js'].includes(name)&&!actual;const file=path.resolve(local?dir:root,name);if(!file.startsWith(path.resolve(root))&&!file.startsWith(dir)){res.writeHead(403).end();return}fs.readFile(file,(err,buf)=>{if(err){res.writeHead(404).end();return}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css','.png':'image/png'})[path.extname(file)]||'application/octet-stream');let data=buf;if(name==='game.js')data=data.toString().replace('if(previewKey)startLivePreview();else renderHome();',`window.nativeHarness={select(key){startFreeGame(GAMES.findIndex(g=>g.key===key))},games:GAMES,records:()=>state.records};if(previewKey)startLivePreview();else renderHome();`);if(name==='party-approved-games.js')data=data.toString().replace('return {dispose,ready};',`window.nativeRuns=window.nativeRuns||[];window.nativeRuns.push({snapshot:()=>({id:current.id,time,score,disposed,active,ended,raf,sources:sources.size,pointer,axisX:held.axisX||0,axisY:held.axisY||0,state:JSON.parse(JSON.stringify(state))})});return {dispose,ready};`);res.end(data)})});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{for(const [width,height] of [[360,640],[390,600]]){const page=await browser.newPage({viewport:{width,height},hasTouch:true});page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{if(r.url().includes('party-approved-arcade.html'))report.errors.push('OLD TEST SHELL REQUESTED')});await page.route('https://**',r=>r.abort());await page.clock.install();await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.clock.pauseAt(new Date(Date.now()+1000));await page.evaluate(()=>{window.exposure=[];new MutationObserver(()=>{if(document.querySelector('iframe:not([data-live-preview]),.approved-game #grid,.approved-game #veil,.approved-game #retry')||document.body.innerText.includes('TWELVE ARCADE'))window.exposure.push(document.body.innerText.slice(0,100))}).observe(document.body,{childList:true,subtree:true})});
const snap=()=>page.evaluate(()=>window.nativeRuns.at(-1).snapshot());
async function nextReady(){for(let i=0;i<12;i++){if(await page.locator('#readyBtn').count())return;const btn=page.locator('#screen button').filter({hasText:/START|READY|スタート|準備|次へ|プレイ/}).first();if(await btn.count())await btn.click();else throw Error('No intro action: '+await page.locator('#screen').innerText());await page.clock.runFor(150)}throw Error('Missing ready')}
async function launch(key){await page.evaluate(k=>nativeHarness.select(k),key);await nextReady();await page.locator('#readyBtn').click();await page.clock.runFor(3000);assert.equal((await snap()).active,true);assert.equal(await page.locator('iframe').count(),0);const rects=await page.locator('.approved-game canvas,.approved-game .season-actions,.approved-game .season-actions button,.approved-game .party-stick').evaluateAll(es=>es.map(el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height}}));for(const r of rects)assert(r.x>=0&&r.y>=0&&r.x+r.w<=width+1&&r.y+r.h<=height+1,JSON.stringify(r));return rects}
async function finish(key){if(key==='juiceArcadeMob'){await page.locator('[data-arcade-action]').dispatchEvent('pointerdown',{pointerId:1});await page.clock.runFor(1100);await page.locator('[data-arcade-action]').dispatchEvent('pointerup',{pointerId:1})}await page.clock.fastForward(11000);assert.equal(await page.locator('#soloReplay').count(),1);const s=await snap();assert(s.disposed&&!s.active&&s.raf===0&&s.sources===0);assert.equal(await page.locator('.approved-game').count(),0);return s.score}
for(const [n,key] of ['juiceArcadeMob','rallyArcadeMob','potteryArcadeMob'].entries()){
const rects=await launch(key);await page.screenshot({path:path.join(dir,`${key}-${width}.png`)});const score=await finish(key);
// All three real result controls, rather than inspecting only result appearance.
await page.locator('#soloReplay').click();await nextReady();await page.locator('#readyBtn').evaluate(b=>{b.click();b.click();b.click()});await page.clock.runFor(3000);assert((await snap()).active);assert.equal(await page.locator('.approved-game').count(),1);await finish(key);await page.locator('#soloOther').click();await page.clock.runFor(100);assert(await page.locator('[data-game],[data-free-game]').count()>0);
const next=['rallyArcadeMob','potteryArcadeMob','juiceArcadeMob'][n],index=await page.evaluate(k=>nativeHarness.games.findIndex(g=>g.key===k),next);await page.locator(`[data-game="${index}"],[data-free-game="${index}"]`).click();await nextReady();await page.locator('#readyBtn').click();await page.clock.runFor(3000);assert((await snap()).active);await finish(next);await page.locator('#soloHome').click();assert.equal(await page.locator('.approved-game,#soloReplay').count(),0);
// End/cancel input ownership and abort an active session; dispatch to detached old DOM too.
await launch(key);if(key!=='rallyArcadeMob'){const btn=page.locator('[data-arcade-action]');await btn.dispatchEvent('pointerdown',{pointerId:11});await btn.dispatchEvent('pointerdown',{pointerId:12});await page.clock.runFor(150);await btn.dispatchEvent('pointerup',{pointerId:12});assert.equal((await snap()).sources,1);await btn.dispatchEvent('pointercancel',{pointerId:11});assert.equal((await snap()).sources,0);assert.equal((await snap()).pointer,null)}
if(key!=='juiceArcadeMob'){const pad=page.locator('[data-arcade-stick]');const r=await pad.boundingBox();await pad.evaluate(el=>el.addEventListener('pointerdown',e=>window.lastNativePointer=e.pointerId,{once:true}));await page.mouse.move(r.x+r.width*.8,r.y+r.height*.8);await page.mouse.down();assert(Math.abs((await snap()).axisX)>.1);await pad.dispatchEvent('pointercancel',{pointerId:await page.evaluate(()=>window.lastNativePointer)});await page.mouse.up();assert.equal((await snap()).axisX,0);assert.equal((await snap()).axisY,0)}
await page.evaluate(()=>window.detachedAction=document.querySelector('[data-arcade-action]'));await page.locator('#homeBtn').click();const frozen=await snap();await page.evaluate(()=>window.detachedAction?.dispatchEvent(new PointerEvent('pointerdown',{pointerId:88,bubbles:true})));await page.clock.fastForward(15000);assert.deepEqual(await snap(),frozen);assert.equal(await page.locator('.approved-game,#soloReplay').count(),0);
// Abandon while awaiting the shared countdown. Its completion cannot revive old games.
await page.evaluate(k=>nativeHarness.select(k),key);await nextReady();await page.locator('#readyBtn').click();await page.clock.runFor(100);await page.locator('#homeBtn').dispatchEvent('click');await page.clock.runFor(4000);assert.equal(await page.locator('.approved-game,.countdown-layer').count(),0);assert((await snap()).disposed);
report.checks.push({width,height,key,score,rects,paths:['start','finish','replay','other-game','result-home','in-game-home','countdown-abort','rapid-ready','pointer-end-cancel','detached-input']});console.log('PASS',width,key)
}
assert.deepEqual(await page.evaluate(()=>window.exposure),[]);const runs=await page.evaluate(()=>window.nativeRuns.map(r=>r.snapshot()));assert(runs.every(r=>r.disposed&&r.raf===0&&r.sources===0));await page.close()}
assert.deepEqual(report.errors,[]);fs.writeFileSync(path.join(dir,actual?'lifecycle-actual.json':'lifecycle-staged.json'),JSON.stringify(report,null,2));console.log('PASS lifecycle',report.checks.length)}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});


