const artifactDir=require('./expanded-harness.cjs').output;
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright'),{start,ready}=require('./expanded-harness.cjs');
(async()=>{const{server,url}=await start(process.argv.includes('--actual')),b=await chromium.launch({headless:true,channel:'msedge'}),errors=[];try{const p=await b.newPage({viewport:{width:390,height:600}});p.on('pageerror',e=>errors.push(e.message));await p.route('https://**',r=>r.abort());await p.clock.install();await p.goto(url);await p.clock.pauseAt(new Date(Date.now()+500));for(const key of JSON.parse(fs.readFileSync(path.join(__dirname,'arcade-catalog.json'))).map(a=>a[0])){
await p.evaluate(key=>{const ps=MobPartyCore.roster.slice(0,4).map((c,i)=>({...c,id:'qa'+i,name:'QA '+i,cpu:i>1,characterRank:'B'}));window.qaTeams=[{id:'A',name:'A',members:['qa0','qa2']},{id:'B',name:'B',members:['qa1','qa3']}];testHost.league.configure(ps,qaTeams);window.qaDone=null;testHost.league.run(key,qaTeams,{phase:'qualifier',round:1},points=>window.qaDone=points)},key);
for(let n=0;n<2;n++){await ready(p);await p.clock.fastForward(25000);assert.equal(await p.locator('#nextHuman').count(),1,key);await p.clock.runFor(650);await p.locator('#nextHuman').click();await p.clock.runFor(1000)}
for(let i=0;i<20&&!await p.evaluate(()=>!!qaDone);i++){await p.clock.fastForward(3000);const btn=p.locator('#screen button').first();if(await btn.count())await btn.click()}
const points=await p.evaluate(()=>qaDone);assert(points,key+' no league scores');assert.equal(Object.keys(points).length,4);assert(Object.values(points).every(v=>Number.isFinite(v)&&v>=0&&v<=100));console.log('PASS league',key)}
for(const [width,height] of [[360,640],[390,600],[1280,800]]){await p.setViewportSize({width,height});await p.evaluate(()=>{window.qaFinish=null;window.qaValid=true;testHost.begin(-1);MobPartyGames.create({screen:document.querySelector('#screen'),esc:s=>s,valid:()=>qaValid,begin:()=>1,top(){scrollTo(0,0)},beep(){},round:()=>0,solo:()=>false,games:[{key:'deathGameChallenge',title:'Death'}],teams:()=>MobPartyCore.roster.slice(0,3).map((c,i)=>({name:'Team '+i,members:[{...c,id:'d'+i,name:'Entrant '+i,cpu:true}]})),representatives(){},finish(i,s){qaFinish=s}}).start(0)});
for(let i=0;i<20&&!await p.locator('#finalDoors').count();i++){const btn=p.locator('#eventChoices button').first();if(await btn.count())await btn.click();else await p.clock.runFor(200)}
assert.equal(await p.locator('.party-final-door').count(),3);assert.equal(await p.locator('.party-final-door img').count(),1);await p.clock.runFor(1400);await p.screenshot({path:path.join(artifactDir,'death-'+width+'.png'),animations:'disabled'});const r=await p.locator('#eventChoices button').boundingBox();assert(r.y+r.height<=height&&r.height>=44);const winner=await p.locator('.is-winner img').getAttribute('alt');await p.locator('#eventChoices button').click();await p.locator('#eventChoices button').click();const slots=await p.evaluate(()=>qaFinish);assert.equal(slots.find(s=>s.score===100).name,winner);console.log('PASS death',width)}assert.deepEqual(errors,[]);console.log('PASS league/death')}finally{await b.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
