const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright'),{start,ready}=require('./visual-refresh-harness.cjs');
const output=path.join(__dirname,'../qa-refresh');fs.mkdirSync(output,{recursive:true});
(async()=>{const {server,url}=await start(),browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),report=[],errors=[];
try{for(const [width,height] of [[320,568],[360,640],[390,600],[430,700]]){
const p=await browser.newPage({viewport:{width,height},hasTouch:true,isMobile:true});p.on('pageerror',e=>errors.push(e.stack));await p.route('https://**',r=>r.abort());await p.goto(url);await p.clock.install();
const fit=async s=>{const r=await p.locator(s).boundingBox();assert.ok(r&&r.x>=-1&&r.y>=-1&&r.x+r.width<=width+1&&r.y+r.height<=height+1,s+JSON.stringify(r));return r};
const spin=async()=>{await p.locator('#arenaSpin').tap();await p.evaluate(()=>document.getAnimations().filter(a=>a.effect?.target?.id==='arenaWheel').forEach(a=>a.finish()));await p.clock.runFor(100);await p.locator('#arenaSpin').tap();await p.clock.runFor(1500);if(await p.locator('#arenaLitNext').count())await p.locator('#arenaLitNext').tap()};
for(const [mode,n] of [['solo40',40],['solo80',80],['tag20',20],['tag40',40],['crew20',20]]){
await p.evaluate(()=>testHost.home());await p.locator('#partyArena').tap();await p.locator('#arenaMode').selectOption(mode);await p.locator('#arenaHumans').selectOption('0');await p.locator('#arenaEnter').tap();await p.clock.runFor(2600);await p.evaluate(()=>document.getAnimations().filter(a=>a.animationName==='arenaRuleReveal').forEach(a=>a.finish()));await fit('#arenaOpeningGo');if(mode==='solo40')await p.screenshot({path:path.join(output,`opening-${width}.png`)});await p.locator('#arenaOpeningGo').tap();await fit('#arenaSpin');assert.equal(await p.locator('.arena-candidates li').count(),5);if(mode==='solo40')await p.screenshot({path:path.join(output,`roulette-${width}.png`)});await spin();assert.equal(await p.locator('.arena-scorecard').count(),n);await fit('#arenaNextRound');await fit('.arena-score-list');await p.locator('.arena-score-list').evaluate(el=>el.scrollTop=el.scrollHeight);assert.ok(await p.locator('.arena-score-list').evaluate(el=>el.scrollTop>0));await fit('.arena-scorecard:last-child');if(mode==='solo80')await p.screenshot({path:path.join(output,`results-bottom-${width}.png`)});await p.locator('#arenaTotalTab').tap();assert.equal(await p.locator('.arena-scorecard').count(),n);if(mode==='crew20')await p.screenshot({path:path.join(output,`crew-results-${width}.png`)});const old=await p.evaluate(()=>JSON.parse(localStorage.getItem('mob-game-king-arena-v1')));await p.evaluate(()=>testHost.home());await p.locator('#partyArena').tap();await p.locator('#arenaResume').tap();assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('mob-game-king-arena-v1')).totals),old.totals);report.push({width,height,mode,allRows:n,scroll:true,resume:true});
}
// Winning presentation from a completed real rules round with previously lit teams.
await p.evaluate(()=>{const s=JSON.parse(localStorage.getItem('mob-game-king-arena-v1'));s.champion=null;s.pending=null;s.lit=s.teams.map(t=>t.id);s.teams.forEach(t=>s.totals[t.id]=50);const q=MobArenaRules.prepare(s);q.active.forEach(id=>q.representatives[id]=s.teams.find(t=>t.id===id).members.slice(0,q.count));MobArenaRules.submit(s,q.id,Object.fromEntries(q.active.flatMap((id,i)=>q.representatives[id].map(pid=>[pid,i===0?100:0]))));localStorage.setItem('mob-game-king-arena-v1',JSON.stringify(s));testHost.home()});await p.locator('#partyArena').tap();await p.locator('#arenaResume').tap();await fit('#arenaWallpaper');await fit('#arenaFinish');await p.screenshot({path:path.join(output,`champion-${width}.png`)});
await p.evaluate(()=>testHost.home());await ready(p,'tableclothPull');assert.equal(await p.locator('.cloth-doll-v202').count(),7);await p.screenshot({path:path.join(output,`cloth-${width}.png`)});await p.evaluate(()=>testHost.home());await ready(p,'stack');await p.screenshot({path:path.join(output,`stack-${width}.png`)});
await p.close();console.log('PASS mobile',width,height)}
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'browser-report.json'),JSON.stringify({report,errors},null,2));
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
