const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright'),{start,ready,output}=require(process.env.MOB_ARENA_HARNESS||'./visual-refresh-harness.cjs');
(async()=>{const {server,url}=await start(),b=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),report=[],errors=[];try{for(const [width,height] of [[360,640],[390,600]]){const p=await b.newPage({viewport:{width,height},hasTouch:true,isMobile:true,acceptDownloads:true});p.on('pageerror',e=>errors.push(e.message));await p.route('https://**',r=>r.abort());await p.clock.install();await p.goto(url);await p.clock.pauseAt(new Date(await p.evaluate(()=>Date.now()+1000)));
const check=async selectors=>{for(const sel of selectors){const r=await p.locator(sel).last().boundingBox();assert.ok(r&&r.x>=-1&&r.y>=-1&&r.x+r.width<=width+1&&r.y+r.height<=height+1,sel+JSON.stringify(r));if(sel.includes('button')||sel.startsWith('#arena'))assert.ok(r.height>=43,sel+' small')}};
const spin=async()=>{await p.locator('#arenaSpin').tap();await p.evaluate(()=>document.getAnimations().filter(a=>a.effect?.target?.id==='arenaWheel').forEach(a=>a.finish()));await p.clock.runFor(50);await p.locator('#arenaSpin').tap();await p.clock.runFor(2000);if(await p.locator('#arenaLitNext').count())await p.locator('#arenaLitNext').tap()};
for(const [mode,teams,players] of [['solo40',40,40],['solo80',80,80],['tag20',20,40],['tag40',40,80],['crew20',20,80]]){await p.locator('#partyArena').tap();await p.locator('#arenaMode').selectOption(mode);await p.locator('#arenaHumans').selectOption('0');await p.locator('#arenaEnter').tap();await p.locator('#arenaOpeningGo').tap();const s=await p.evaluate(()=>JSON.parse(localStorage.getItem('mob-game-king-arena-v1')));assert.equal(s.teams.length,teams);assert.equal(s.players.length,players);assert.equal(new Set(s.players.map(x=>x.img)).size,players);assert.equal(s.pending.choices.length,5);await check(['#arenaSpin']);if(mode==='solo40')await p.screenshot({path:path.join(output,'roulette-'+width+'.png')});await spin();assert.equal(await p.locator('.arena-scorecard').count(),teams);await check(['#arenaNextRound','.arena-score-list']);await p.locator('#arenaTotalTab').tap();assert.equal(await p.locator('.arena-scorecard').count(),teams);await p.screenshot({path:path.join(output,mode+'-'+width+'.png')});report.push({width,mode,teams,players,roundComplete:true});await p.evaluate(()=>testHost.home())}
// Real human selection and representative-only cycle, using an isolated saved tournament.
await p.locator('#partyArena').tap();await p.locator('#arenaMode').selectOption('crew20');await p.locator('#arenaHumans').selectOption('1');await p.locator('#arenaEnter').tap();await p.locator('#partyConfirm').tap();await p.locator('#arenaBegin').tap();await p.evaluate(()=>{const s=JSON.parse(localStorage.getItem('mob-game-king-arena-v1'));s.round=1;s.pending=null;const q=MobArenaRules.prepare(s);q.key='juiceArcadeMob';if(!q.choices.includes(q.key))q.choices[0]=q.key;q.revealed=true;s.phase='play';localStorage.setItem('mob-game-king-arena-v1',JSON.stringify(s));testHost.home()});await p.locator('#partyArena').tap();await p.locator('#arenaResume').tap();assert.equal(await p.locator('[data-arena-rep]').count(),4);await p.locator('[data-arena-rep]').nth(0).tap();await p.locator('[data-arena-rep]').nth(1).tap();await check(['#arenaRepConfirm']);await p.locator('#arenaRepConfirm').tap();await ready(p);await p.locator('[data-arcade-action]').dispatchEvent('pointerdown',{pointerId:10,pointerType:'touch'});await p.clock.runFor(1100);await p.locator('[data-arcade-action]').dispatchEvent('pointerup',{pointerId:10,pointerType:'touch'});await p.clock.runFor(1700);await p.locator('#nextHuman').tap();await p.clock.runFor(3000);if(await p.locator('#arenaLitNext').count())await p.locator('#arenaLitNext').tap();const result=await p.evaluate(()=>JSON.parse(localStorage.getItem('mob-game-king-arena-v1')));assert.equal(result.last.rows.find(r=>r.id==='A0').members.length,2);const before=JSON.stringify(result.totals);await p.evaluate(()=>testHost.home());await p.locator('#partyArena').tap();await p.locator('#arenaResume').tap();assert.equal(await p.evaluate(()=>JSON.stringify(JSON.parse(localStorage.getItem('mob-game-king-arena-v1')).totals)),before);
// A field already lit at the start can crown an actual simulated CPU winner.
await p.evaluate(()=>{const s=JSON.parse(localStorage.getItem('mob-game-king-arena-v1'));s.players.forEach(p=>p.cpu=true);s.totals=Object.fromEntries(s.teams.map(t=>[t.id,50]));s.lit=s.teams.map(t=>t.id);s.phase='draw';s.pending=null;s.last=null;MobArenaRules.prepare(s);localStorage.setItem('mob-game-king-arena-v1',JSON.stringify(s));testHost.home()});await p.locator('#partyArena').tap();await p.locator('#arenaResume').tap();for(let i=0;i<12&&!await p.locator('#arenaWallpaper').count();i++){await spin();if(await p.locator('#arenaWallpaper').count())break;await p.locator('#arenaNextRound').tap()}assert.equal(await p.locator('#arenaWallpaper').count(),1);await check(['#arenaWallpaper']);await p.screenshot({path:path.join(output,'champion-'+width+'.png')});await p.locator('#arenaWallpaper').tap();await p.waitForFunction(()=>!document.querySelector('#studioSaveWallpaper').disabled);assert.equal(await p.locator('[data-tab="draw"]').count(),0);
for(const tab of ['design','layout','text','stamp','effects']){await p.locator(`[data-tab="${tab}"]`).tap();await check(['#studioSaveWallpaper','#studioSaveCard','#studioCanvas']);assert.ok((await p.locator('#studioCanvas').boundingBox()).height>=45)}
await p.locator('[data-tab="text"]').tap();await p.locator('#studioTextAdd').tap();await p.locator('#studioTextValue').fill('モブくんはゲーム王');await p.locator('#studioTextValue').dispatchEvent('change');await p.locator('#studioTextAdd').tap();await p.locator('#studioTextDelete').tap();assert.equal(await p.locator('#studioTextLayer option').count(),1);
await p.locator('[data-tab="stamp"]').tap();assert.equal(await p.locator('[data-toy]').count(),8);for(const button of await p.locator('[data-toy]').all()){await button.tap();await p.locator('#studioCanvas').tap()}await p.screenshot({path:path.join(output,'studio-'+width+'.png')});
const draft=await p.evaluate(()=>{const key=Object.keys(localStorage).find(k=>k.startsWith('mob-victory-design-v2:'));return {key,model:JSON.parse(localStorage.getItem(key))}});assert.equal(draft.model.edits.wallpaper.filter(a=>a.type==='stamp').length,8);assert.equal(draft.model.edits.wallpaper.filter(a=>a.type==='text').length,1);
const download=p.waitForEvent('download');await p.locator('#studioSaveWallpaper').tap();const d=await download;await d.saveAs(path.join(output,'wallpaper-'+width+'.png'));await p.locator('#studioDone').tap();await p.locator('#arenaWallpaper').tap();await p.waitForFunction(()=>!document.querySelector('#studioSaveWallpaper').disabled);assert.equal(await p.evaluate(key=>JSON.parse(localStorage.getItem(key)).edits.wallpaper.length,draft.key),9);
await p.evaluate(()=>{const out=document.createElement('canvas');out.width=800;out.height=400;const c=out.getContext('2d');c.fillStyle='#e8edf3';c.fillRect(0,0,800,400);Object.keys(MobVictoryStamps.labels).forEach((id,i)=>MobVictoryStamps.draw(c,id,100+(i%4)*200,100+Math.floor(i/4)*200,190));window.stampGallery=out.toDataURL()});const png=await p.evaluate(()=>stampGallery);fs.writeFileSync(path.join(output,'stamps.png'),Buffer.from(png.split(',')[1],'base64'));
await p.close();console.log('PASS arena + studio',width,height)}assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'arena-browser.json'),JSON.stringify({report,errors},null,2))}finally{await b.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
