const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),output=fs.mkdtempSync(path.join(os.tmpdir(),'mob-balance-'));
const hooks=`window.balanceTest={start(key){invalidateGameRun();state=freshState();state.freePlay=true;state.modeKey='solo';const i=GAMES.findIndex(g=>g.key===key);state.freeGameIndex=i;state.freePlayerId=PLAYERS[0].id;partyActivePlayer=PLAYERS[0];const id=beginGameRun(i);countdown=async()=>true;const name='start'+key[0].toUpperCase()+key.slice(1);eval(name)(PLAYERS[0],0,id);},records(){return state.records}};`;
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,data)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png'})[path.extname(file)]||'application/octet-stream');if(path.basename(file)==='game.js')data=data.toString().replace(/if\(previewKey\)startLivePreview\(\);else renderHome\(\);/,hooks+'renderHome();');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 for(const [width,height] of [[360,640],[390,600]]){
  const page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route(/^https?:\/\/(?!127\.0\.0\.1)/,r=>r.abort());await page.goto('http://127.0.0.1:'+server.address().port+'/index.html');
  const start=async key=>{await page.evaluate(k=>window.balanceTest.start(k),key);await page.waitForTimeout(100);};
  const check=async(key,fn)=>{if(process.env.BALANCE_CASES&&!process.env.BALANCE_CASES.split(',').includes(key))return;await start(key);await fn();};
  const visible=async selector=>{const boxes=await page.locator(selector).evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().toJSON()));assert.ok(boxes.length);assert.ok(boxes.every(r=>r.width>0&&r.height>=43&&r.top>=0&&r.left>=-1&&r.right<=width+1&&r.bottom<=height+1),selector+JSON.stringify(boxes));};
  await check('tankMob',async()=>{await visible('[data-fire]');await page.locator('[data-fire=up]').dispatchEvent('pointerdown');assert.ok(await page.locator('.tank-shell-shot-v132').count());await page.screenshot({path:path.join(output,`tank-${width}.png`)});});
  await check('electricMaze',async()=>{assert.equal(await page.locator('.maze-wall-v119').count(),4);assert.equal(await page.locator('.electric-orb').count(),7);const square=await page.locator('#electricStage').boundingBox();assert.ok(square.width>240&&Math.abs(square.width-square.height)<2,JSON.stringify(square));await page.screenshot({path:path.join(output,`electric-${width}.png`)});
    await page.evaluate(()=>{const stage=document.querySelector('#electricStage'),orb=document.querySelectorAll('.electric-orb')[4];const chase=()=>{if(!stage.isConnected||document.querySelector('.electric-orb.spent'))return;const r=stage.getBoundingClientRect();stage.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,clientX:r.left+stage.clientLeft+parseFloat(orb.style.left),clientY:r.top+stage.clientTop+parseFloat(orb.style.top)}));requestAnimationFrame(chase);};requestAnimationFrame(chase);});
    await page.waitForFunction(()=>document.querySelector('.electric-orb.spent'),null,{timeout:5000});assert.match(await page.locator('#electricStatus').textContent(),/STUN/);await page.waitForTimeout(300);assert.equal(await page.locator('.electric-orb').count(),6);
  });
  await check('monsterMaster',async()=>{const pad=await page.locator('#ballPad135').boundingBox();assert.ok(pad.width>260&&pad.y+pad.height<=height,JSON.stringify(pad));await page.screenshot({path:path.join(output,`drawing-${width}.png`)});await page.waitForTimeout(3100);assert.equal(await page.locator('.ball-design-mode').count(),0);const small=await page.locator('#ballPad135').boundingBox();assert.ok(small.width>=44&&small.width<=80);await visible('#ballPad135');const launched=await page.locator('#ballPad135').evaluate(pad=>{const r=pad.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2;pad.dispatchEvent(new PointerEvent('pointerdown',{pointerId:10,clientX:x,clientY:y}));pad.dispatchEvent(new PointerEvent('pointerup',{pointerId:10,clientX:x,clientY:y-100}));return document.querySelectorAll('.master-projectile-v135').length;});assert.ok(launched);await page.screenshot({path:path.join(output,`throw-${width}.png`)});});
  await check('tamaireMob',async()=>{assert.equal(await page.locator('.tama-basket-v170').count(),2);await visible('.tama-basket-v170');const stage=await page.locator('#tamaStage170').boundingBox();for(const dx of [-20,20]){const x=stage.x+stage.width/2,y=stage.y+stage.height*.82;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+dx,y-60,{steps:3});await page.mouse.up();await page.waitForTimeout(1400);}assert.equal(Number(await page.locator('#tamaIn170').innerText()),2);assert.equal(Number(await page.locator('#tamaScore170').innerText()),20);await page.screenshot({path:path.join(output,`tamaire-${width}.png`)});});
  await check('atafutaSurvival',async()=>{assert.equal(await page.locator('.trampoline-rock').count(),2);await visible('.survival-controls-v137 button');});
  await check('waveMaster',async()=>{await page.locator('#soulTap140').dispatchEvent('pointerdown');await page.waitForTimeout(7000);assert.match(await page.locator('#waveZHint140').textContent(),/TIME UP/);});
  await check('battleRoyaleMob',async()=>{await visible('.br-main-controls-v139 button');const mob=await page.locator('.br-actor-v138.player-v138').boundingBox(),stage=await page.locator('#brStage138').boundingBox();assert.ok(mob.y+mob.height<=stage.y+stage.height,JSON.stringify({mob,stage}));await page.screenshot({path:path.join(output,`arena-${width}.png`)});});
  await check('monsterBoxMob',async()=>{await visible('#mbJump138');assert.equal(await page.locator('#mbJump138').innerText(),'JUMP');const before=await page.locator('#mbMob138').evaluate(el=>parseFloat(el.style.top));await page.locator('#mbJump138').dispatchEvent('pointerdown');await page.waitForTimeout(140);assert.ok(await page.locator('#mbMob138').evaluate(el=>parseFloat(el.style.top))<before-10);await page.screenshot({path:path.join(output,`board-${width}.png`)});});
  await check('hurdleRun',async()=>{await page.evaluate(()=>{const stage=document.querySelector('#hurdleStage160');const bot=()=>{if(!stage.isConnected||document.querySelector('.hurdle-result-overlay-v160'))return;const origin=stage.getBoundingClientRect().left+stage.clientLeft+82;for(const gate of stage.querySelectorAll('[data-hurdle]')){const dx=gate.getBoundingClientRect().left-origin;if(dx>45&&dx<53&&!gate.dataset.jumped){gate.dataset.jumped='yes';document.querySelector('#hurdleJump160').dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));}}requestAnimationFrame(bot);};requestAnimationFrame(bot);});await page.locator('.hurdle-result-card-v160').waitFor({timeout:20000});assert.match(await page.locator('.hurdle-result-card-v160').innerText(),/NO HIT 10 \/ 10/);});
  await check('sphereMob',async()=>{assert.equal(await page.locator('.rock-aim').count(),1);await visible('#rockDash');await page.screenshot({path:path.join(output,`sphere-${width}.png`)});});
  await check('airHockeyMob',async()=>{assert.ok((await page.locator('.airh-goal.top-v174').boundingBox()).width>140);});
  await check('findMob',async()=>{assert.equal(await page.locator('.find-decoy-mob-v205 img').count(),7);assert.ok(await page.locator('#findMob203 img').evaluate(img=>img.complete&&img.naturalWidth>0));await page.screenshot({path:path.join(output,`find-${width}.png`)});});
  await check('mobPinball',async()=>{await visible('#pinballDrop160');await page.locator('#pinballDrop160').click();await page.waitForFunction(()=>document.querySelector('#pinballLive160')?.textContent.includes('PT'),null,{timeout:45000});
  const slots=await page.locator('.pinball-slot-row-v160').boundingBox(),stage=await page.locator('#pinballStage160').boundingBox();assert.ok(slots.x>=stage.x&&slots.x+slots.width<=stage.x+stage.width+1&&slots.y>=stage.y&&slots.y+slots.height<=stage.y+stage.height+1,JSON.stringify({slots,stage}));await page.screenshot({path:path.join(output,`pinball-${width}.png`)});});
  assert.deepEqual(errors,[]);await page.close();
 }
 console.log('Passed at both mobile widths: '+(process.env.BALANCE_CASES||'all representative cases'));console.log(output);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
