const artifactDir=require('./league-upgrade-harness.cjs').output;
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright'),{start}=require('./league-upgrade-harness.cjs');
(async()=>{const {server,url}=await start(),b=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),errors=[],report=[];try{for(const [width,height] of [[320,640],[390,600],[430,932]]){const page=await b.newPage({viewport:{width,height},hasTouch:true});page.on('pageerror',e=>errors.push(e.message));await page.route('https://**',r=>r.abort());await page.goto(url);await page.clock.install();await page.clock.pauseAt(new Date(Date.now()+500));await page.addScriptTag({content:fs.readFileSync(path.join(__dirname,'../party-league-ui.js'),'utf8').replace('return {setup,stop,active:', 'return {seed(s,p){league=s;players=p;},state:()=>league,play,results,setup,stop,active:')});
await page.evaluate(()=>{MobPresentation=null;document.querySelector('#screen').innerHTML='';const screen=document.querySelector('#screen'),players=Array.from({length:40},(_,i)=>({...MobPartyCore.roster[i],id:'p'+i,no:i+1,cpu:i>1})),teams=Array.from({length:20},(_,i)=>({id:'L'+i,name:'TEAM '+i,members:['p'+i*2,'p'+(i*2+1)]}));window.calls=[];const api={screen,esc:s=>String(s),clear(){screen.innerHTML=''},top(){scrollTo(0,0)},beep(){},home(){screen.innerHTML='HOME'},title:k=>testHost.games.find(g=>g.key===k)?.title||k,pool:()=>['reaction'],configure(){},run(key,rows,d,done){calls.push({key,rows,d});done(Object.fromEntries(rows.flatMap(t=>t.members.map(p=>[p,80]))))}};window.lplayers=players;window.lteams=teams;window.makeUI=()=>MobPartyLeagueUI.create(api);window.lui=makeUI();window.lstate=MobPartyLeague.create(teams,MobPartyLeague.program(['reaction'],()=>0));lstate.round=1;lui.seed(lstate,players);lui.play();});
assert.equal(await page.locator('.roulette-options li').count(),5);const drawn=await page.evaluate(()=>lstate.pendingRound.choices);assert.equal(new Set(drawn).size,2);await page.locator('#leagueNext').click();for(let i=0;i<2;i++){await page.evaluate(()=>document.getAnimations().filter(a=>a.effect?.target?.id==='leagueWheel').forEach(a=>a.finish()));await page.clock.runFor(700);}await page.waitForFunction(()=>!document.querySelector('#leagueNext').disabled);assert.equal(await page.locator('#roulettePicks b').count(),2);await page.screenshot({path:path.join(artifactDir,'roulette-'+width+'.png')});const overflow=await page.locator('#leagueNext').evaluate(e=>e.getBoundingClientRect().bottom>innerHeight+1);assert.equal(overflow,false,width+' roulette button');await page.locator('#leagueNext').click();await page.locator('#leagueNext').click();await page.locator('#leagueChoice0').click();assert.equal(await page.locator('#leagueChoice0').isDisabled(),true);await page.locator('#leagueChoice1').click();const assignments=await page.evaluate(()=>({...lstate.pendingRound.progress.assignments}));assert.notEqual(assignments.p0,assignments.p1);
// Re-create UI from its durable snapshot before executing any challenge.
await page.evaluate(()=>{lui.stop();lui=makeUI();lui.setup()});await page.locator('#leagueResume').click();assert.deepEqual(await page.evaluate(()=>lui.state().pendingRound.choices),drawn);assert.deepEqual(await page.evaluate(()=>lui.state().pendingRound.progress.assignments),assignments);
for(let n=0;n<20&&await page.evaluate(()=>!lui.state().history.length);n++){const next=page.locator('#leagueNext');if(await next.count())await next.click();else throw Error('Missing challenge continuation')};assert.equal(await page.evaluate(()=>lui.state().history.length),1);assert.equal(await page.evaluate(()=>calls.length),40);assert.equal(await page.evaluate(()=>lui.state().history[0].teamPoints.L0),160);
// One representative from a mixed/human pair; CPU teams are selected once.
await page.evaluate(()=>{lui.stop();calls.length=0;lstate=MobPartyLeague.create(lteams,MobPartyLeague.program(['reaction'],()=>0));lstate.round=4;lui=makeUI();lui.seed(lstate,lplayers);lui.play()});await page.locator('#leagueNext').click();await page.evaluate(()=>document.getAnimations().filter(a=>a.effect?.target?.id==='leagueWheel').forEach(a=>a.finish()));await page.clock.runFor(100);await page.locator('#leagueNext').click();await page.locator('#leagueRep1').click();for(let n=0;n<8&&await page.evaluate(()=>!lstate.history.length);n++)await page.locator('#leagueNext').click();assert.equal(await page.evaluate(()=>calls.length),1);assert.equal(await page.evaluate(()=>calls[0].rows.every(t=>t.members.length===1)),true);assert.equal(await page.evaluate(()=>lstate.history[0].teamPoints.L0),160);assert.equal(await page.evaluate(()=>lstate.history[0].points.p0),0);assert.equal(await page.evaluate(()=>lstate.history[0].representatives.L0),'p1');
// Victory animation appears before rankings, lasts five seconds, and stops cleanly.
await page.evaluate(()=>{lstate.phase='final';lstate.active=lstate.active.slice(0,10);lstate.champion='L0';lui.results({event:{type:'champion',ids:['L0']},record:{...lstate.history[0],phase:'final',litBefore:['L0']}})});assert.equal(await page.locator('.champion-podium img').count(),2);assert.equal(await page.locator('.league-rank').count(),0);await page.clock.runFor(1200);await page.screenshot({path:path.join(artifactDir,'champion-'+width+'.png')});assert.ok(await page.locator('#championContinue').evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight+1));await page.clock.runFor(3790);assert.equal(await page.locator('.league-champion-cinema').count(),1);await page.clock.runFor(20);assert.ok(await page.locator('.league-rank').count());await page.evaluate(()=>{delete lstate.celebratedChampion;lui.results({event:{type:'champion',ids:['L0']},record:{...lstate.history[0],phase:'final',litBefore:['L0']}});lui.stop();document.querySelector('#screen').innerHTML='HOME'});await page.clock.runFor(6000);assert.equal(await page.locator('#screen').textContent(),'HOME');report.push({width,roulette:drawn,assignmentResume:true,representative:1,cinemaMs:5000});await page.close();console.log('LEAGUE PASS',width)}assert.deepEqual(errors,[]);fs.writeFileSync(path.join(artifactDir,'league-browser.json'),JSON.stringify({report,errors},null,2));}finally{await b.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
