const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),output=fs.mkdtempSync(path.join(os.tmpdir(),'mob-new-leagues-'));
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,data)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{
for(const [width,height] of [[360,640],[390,600]]){const page=await browser.newPage({viewport:{width,height},acceptDownloads:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/tests/league-variants-preview.html`);
async function check(label){await page.waitForTimeout(180);const bad=await page.locator('.variant-league>button,.variant-row,.variant-league>label,.variant-league h1,.ranking-scope').evaluateAll(nodes=>nodes.filter(el=>{const r=el.getBoundingClientRect();return r.x<0||r.y<0||r.right>innerWidth+1||r.bottom>innerHeight+1||(el.tagName==='BUTTON'&&r.height<44);}).map(el=>({tag:el.tagName,text:el.textContent,rect:el.getBoundingClientRect().toJSON()})));assert.deepEqual(bad,[],label);await page.screenshot({path:path.join(output,`${label}-${width}.png`)});}
for(const mode of ['crew','king']){await page.evaluate(m=>startPreview(m),mode);await check(mode+'-setup');await page.selectOption('#variantCount','0');await page.click('#variantSelect');await page.click('#variantStart');await check(mode+'-opening');await page.evaluate(()=>advancePreview('このゲームの順位'));await check(mode+'-round');await page.evaluate(()=>advancePreview('総合順位'));await check(mode+'-total');await page.evaluate(()=>advancePreview('QUALIFIED'));await check(mode+'-qualified');if(mode==='king')assert.ok(await page.locator('.variant-row em').count());await page.evaluate(()=>advancePreview('優勝記念コレクション'));await check(mode+'-collection');await page.click('#variantSave');await page.waitForFunction(()=>!document.querySelector('#studioSaveCard').disabled);await page.screenshot({path:path.join(output,`${mode}-studio-${width}.png`)});await page.click('[data-format="card"]');await page.screenshot({path:path.join(output,`${mode}-card-${width}.png`)});const download=page.waitForEvent('download');await page.click('#studioSaveCard');await(await download).saveAs(path.join(output,`${mode}-card-${width}-export.png`));}
await page.evaluate(()=>startPreview('king'));await page.selectOption('#variantCount','20');await page.click('#variantSelect');for(let i=0;i<20;i++)await page.click('#partyConfirm');assert.equal(await page.locator('[data-assignment]').count(),20);await page.selectOption('[data-assignment="19"]','3');await check('twenty-humans');await page.click('#variantStart');assert.equal(await page.evaluate(()=>previewPlayers.filter(p=>!p.cpu).length),20);assert.equal(await page.evaluate(()=>previewTeams.find(t=>t.members.includes('p20')).division),3);assert.deepEqual(errors,[]);await page.close();}
console.log('New league setup, both ranking scopes, qualifier badges, twenty humans, crew/solo card exports and mobile bounds passed.');console.log(output);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
