const artifactDir=require('./league-upgrade-harness.cjs').output;
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright'),{start,ready}=require('./league-upgrade-harness.cjs');
(async()=>{const {server,url}=await start(),browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});const report=[],errors=[];try{
for(const [width,height] of [[320,640],[390,600],[430,932]]){
 const page=await browser.newPage({viewport:{width,height},hasTouch:true,acceptDownloads:true});page.on('pageerror',e=>errors.push(e.message));await page.route('https://**',r=>r.abort());await page.clock.install();await page.goto(url);await page.clock.pauseAt(new Date(Date.now()+500));
 for(const key of ['juiceArcadeMob','lockArcadeMob','cargoArcadeMob','dockingArcadeMob']){await ready(page,key);await page.clock.runFor(30);const boxes=await page.locator('.approved-game canvas,.approved-game .season-actions').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height}}));for(const r of boxes)assert.ok(r.x>=-1&&r.y>=-1&&r.x+r.w<=width+1&&r.y+r.h<=height+1,key+JSON.stringify(r));assert.ok(Math.abs(boxes[0].w/boxes[0].h-400/440)<.01);if(key==='dockingArcadeMob'){const before=await page.evaluate(()=>nativeRuns.at(-1).snapshot());await page.clock.runFor(300);const after=await page.evaluate(()=>nativeRuns.at(-1).snapshot());assert.notDeepEqual(before.state.obstacles,after.state.obstacles);await page.locator('[data-arcade-action]').dispatchEvent('pointerdown',{pointerId:1});await page.clock.runFor(30);assert.equal(await page.locator('#soloReplay').count(),1);}else{await page.clock.fastForward(25000);assert.equal(await page.locator('#soloReplay').count(),1,key);}report.push({width,key,canvas:boxes[0]});await page.locator('#homeBtn').click();}
 await page.goto(url+'/tests/collectibles-preview.html');await page.addStyleTag({url:url+'/party-league-upgrade.css'});await page.locator('#wall').click();await page.waitForFunction(()=>!document.querySelector('#studioSaveCard').disabled);await page.locator('[data-tab="layout"]').click();
 const baseline=await page.locator('canvas').evaluate(c=>c.toDataURL());let box=await page.locator('canvas').boundingBox();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.6,box.y+box.height*.55,{steps:5});await page.mouse.up();await page.clock.runFor(20);assert.notEqual(await page.locator('canvas').evaluate(c=>c.toDataURL()),baseline);await page.locator('#studioUndo').click();assert.equal(await page.locator('canvas').evaluate(c=>c.toDataURL()),baseline);await page.locator('#studioRedo').click();
 await page.locator('#studioScale').fill('150');await page.locator('#studioScale').dispatchEvent('change');assert.equal(await page.locator('#studioScaleValue').textContent(),'150%');await page.locator('[data-format="card"]').click();assert.equal(await page.locator('#studioScaleValue').textContent(),'100%');await page.locator('[data-format="wallpaper"]').click();assert.equal(await page.locator('#studioScaleValue').textContent(),'150%');
 await page.locator('#studioLayoutReset').click();assert.equal(await page.locator('canvas').evaluate(c=>c.toDataURL()),baseline);
 const bad=await page.locator('.champion-studio button,.champion-studio input,.champion-studio select').evaluateAll(es=>es.filter(e=>e.getClientRects().length).filter(e=>{const r=e.getBoundingClientRect();return r.x<0||r.right>innerWidth+1||r.bottom>innerHeight+1||r.y<0||r.width<43||r.height<43}).map(e=>e.id||e.textContent));assert.deepEqual(bad,[],width+' studio bounds');
 await page.screenshot({path:path.join(artifactDir,'studio-'+width+'.png')});
 for(const [target,w,h] of [['Wallpaper',1440,2560],['Card',1260,1760]]){const waiting=page.waitForEvent('download');await page.locator('#studioSave'+target).click();const download=await waiting,file=path.join(artifactDir,''+width+'-'+target+'.png');await download.saveAs(file);const b=fs.readFileSync(file);assert.equal(b.readUInt32BE(16),w);assert.equal(b.readUInt32BE(20),h);if(target==='Card'){const offset=b.indexOf('pHYs');assert.ok(offset>0);assert.equal(b.readUInt32BE(offset+4),20000);}}
 report.push({width,studio:'drag undo redo independent layouts reset PNG exports passed'});await page.close();console.log('PASS',width);
}assert.deepEqual(errors,[]);fs.writeFileSync(path.join(artifactDir,'browser.json'),JSON.stringify({report,errors},null,2));}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
