const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),output=fs.mkdtempSync(path.join(os.tmpdir(),'mob-new-leagues-'));
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,data)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(data);});});

(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{
for(const [width,height] of [[360,640],[390,600]]){const page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route(/^https?:\/\/(?!127\.0\.0\.1)/,r=>r.abort());await page.goto('http://127.0.0.1:'+server.address().port+'/index.html');
async function bounds(selector,label){await page.locator("#screen img").evaluateAll(images=>Promise.all(images.map(img=>img.decode().catch(()=>{}))));const bad=await page.locator(selector).evaluateAll(nodes=>nodes.map(el=>el.closest(".result-scroll-list")||el).filter(el=>{const r=el.getBoundingClientRect();return r.x<0||r.y<0||r.right>innerWidth+1||r.bottom>innerHeight+1;}).map(el=>el.textContent));assert.deepEqual(bad,[],label);await page.screenshot({path:path.join(output,label+'-'+width+'.png')});}
for(const [button,mode] of [['#partyCrew','crew'],['#partyKingLeague','king']]){await page.click(button);await page.selectOption('#variantCount','0');await page.click('#variantSelect');await page.click('#variantStart');await page.locator('.result-announcement button').click();await page.getByRole('heading',{name:'総合順位',exact:true}).waitFor();assert.match(await page.locator('.ranking-scope').innerText(),/CPU自動集計/);await bounds('.variant-row,#variantNext',mode+'-real-result');page.once('dialog',d=>d.accept());await page.click('#homeBtn');}
await page.evaluate(()=>{window.crewEventEntrants=MobPartyCore.roster.slice(0,40).map((c,i)=>({...c,id:'event'+i,teamId:'C'+Math.floor(i/4),team:'CREW '+Math.floor(i/4),cpu:true}));MobLeagueEvents.run({mode:'crew',key:'focusBombMob',screen:document.querySelector('#screen'),esc:s=>s,entrants:crewEventEntrants,valid:()=>true,clear(){},top(){scrollTo(0,0)},beep(){},done(){}});});await page.locator('#eventActions button').click();assert.equal(await page.locator('.event-roster article').count(),8);await bounds('.event-roster article,#eventActions button','crew-bomb-eight');
await page.evaluate(()=>{window.deathRoster=MobPartyCore.roster.slice(0,80);MobPartyGames.create({screen:document.querySelector('#screen'),esc:s=>s,valid:()=>true,begin:()=>1,top(){scrollTo(0,0)},beep(){},round:()=>0,solo:()=>false,games:[{key:'deathGameChallenge',title:'デスゲーム'}],teams:()=>Array.from({length:40},(_,i)=>({name:'CREW PAIR '+i,members:deathRoster.slice(i*2,i*2+2).map((c,j)=>({...c,id:'d'+(i*2+j),cpu:true}))})),representatives(){},finish(){}}).start(0);});await page.locator('#eventChoices button').waitFor();await bounds('.elimination-results article,#eventChoices button','crew-death-entry');for(let i=0;i<20;i++)await page.locator('#eventChoices button').click();await page.getByRole('heading',{name:/ELIMINATED/}).waitFor();await bounds('.elimination-results article,#eventChoices button','crew-death-elimination');assert.deepEqual(errors,[]);await page.close();}
console.log('Actual home navigation and CPU-only stage summaries, eight-player crew bomb heat and eighty-player death paging passed at both mobile sizes.');console.log(output);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
