const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright'),{start,ready,output}=require(process.env.MOB_FIX_HARNESS||'./visual-refresh-harness.cjs');
(async()=>{const {server,url}=await start(),b=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),report=[],errors=[];try{
for(const [width,height] of [[360,640],[390,600]]){
const p=await b.newPage({viewport:{width,height},hasTouch:true,isMobile:true});p.on('pageerror',e=>errors.push(e.message));await p.route('https://**',r=>r.abort());await p.clock.install();await p.goto(url);await p.clock.pauseAt(new Date(await p.evaluate(()=>Date.now()+1000)));
await ready(p,'atafutaSurvival');const session=await p.context().newCDPSession(p),r=await p.locator('#surviveLeft137').boundingBox();await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x+r.width/2,y:r.y+r.height/2}]});await p.clock.runFor(24000);await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});console.log('SURVIVAL END',await p.locator('#screen').innerText(),errors);await p.locator('#soloReplay').tap({timeout:3000});await ready(p);await p.clock.runFor(24000);await p.locator('#soloHome').tap();assert.equal(await p.locator('#partySolo').count(),1);
await p.evaluate(()=>{const players=MobPartyCore.roster.slice(0,4).map((c,i)=>({...c,id:'qa'+i,cpu:i>0})),teams=[{id:'Q0',name:'A',members:['qa0','qa1']},{id:'Q1',name:'B',members:['qa2','qa3']}];testHost.league.configure(players,teams);testHost.league.run('atafutaSurvival',teams,{phase:'qualifier',round:1},r=>window.result=r)});await ready(p);await p.clock.runFor(24000);await p.locator('#nextHuman').tap();await p.clock.runFor(3500);assert.equal(await p.evaluate(()=>Object.keys(window.result||{}).length),4);await p.evaluate(()=>testHost.home());
for(let repeat=0;repeat<2;repeat++){await ready(p,'mobPinball');await p.locator('#pinballDrop160').tap();await p.clock.runFor(30000);await p.locator('#pinballNext160').tap();await p.locator(repeat?'#soloHome':'#soloReplay').tap();if(!repeat)await p.evaluate(()=>testHost.home())}
// Preserve editing while blocking callout/selection/drag on dynamic game content.
const locks=await p.evaluate(()=>{const area=document.createElement('div');area.innerHTML='<span id="qaText">hold text</span><img id="qaImage" src="icon/01.png"><input id="qaInput" value="editable">';document.querySelector('#screen').append(area);const a={};for(const id of ['qaText','qaImage','qaInput']){const el=document.getElementById(id);a[id]={style:getComputedStyle(el).userSelect};for(const type of ['selectstart','contextmenu','dragstart'])a[id][type]=!el.dispatchEvent(new Event(type,{bubbles:true,cancelable:true}));}area.remove();return a});assert.equal(locks.qaText.style,'none');assert.equal(locks.qaImage.dragstart,true);assert.equal(locks.qaText.contextmenu,true);assert.equal(locks.qaInput.style,'text');assert.equal(locks.qaInput.selectstart,false);assert.equal(locks.qaInput.contextmenu,false);
// Resume representative selection using the real league UI and isolated storage.
await p.evaluate(()=>{const players=MobPartyCore.roster.slice(0,40).map((c,i)=>({...c,id:'p'+i,no:i+1,cpu:i!==0})),teams=Array.from({length:20},(_,i)=>({id:'L'+i,name:'TEAM '+i,members:['p'+i*2,'p'+(i*2+1)]})),league=MobPartyLeague.create(teams,MobPartyLeague.program(['reaction'],()=>0));league.round=4;league.pendingRound=MobPartyLeague.next(league,()=>0);localStorage.setItem('mobTagLeagueProgressV2',JSON.stringify({version:2,league,players}));testHost.home()});await p.locator('#partyLeague').tap();await p.locator('#leagueResume').tap();await p.clock.runFor(50);
for(const sel of ['#leagueRep0','#leagueRep1','#leagueRep0 img','#leagueRep1 img']){const box=await p.locator(sel).boundingBox();assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=width&&box.y+box.height<=height,sel+JSON.stringify(box));if(sel.endsWith('img'))assert.ok(box.height<=84);else assert.ok(box.height>=44)}await p.screenshot({path:path.join(output,'representative-'+width+'.png')});await p.locator('#leagueRep0').tap();await p.evaluate(()=>testHost.home());
// Actual qualifier/repechage submissions create the displayed carryover; reload must not add twice.
await p.evaluate(()=>{const data=JSON.parse(localStorage.getItem('mobTagLeagueProgressV2')),L=MobPartyLeague;let league=L.create(data.league.teams,L.program(['reaction'],()=>0)),result;for(let i=0;i<10;i++){const d=L.next(league,()=>0),points=Object.fromEntries(league.active.flatMap(id=>league.teams.find(t=>t.id===id).members.map(p=>[p,100-Number(id.slice(1))*3])));result=L.submit(league,points,d)}league.pendingResult=result;localStorage.setItem('mobTagLeagueProgressV2',JSON.stringify({...data,league}));testHost.home()});await p.locator('#partyLeague').tap();await p.locator('#leagueResume').tap();for(const value of [50,25,18,15,12,10,8,5]){assert.match(await p.locator('.league-carryover').innerText(),new RegExp('決勝スタート：'+value+'pt'));await p.locator('#leagueNext').tap()}await p.evaluate(()=>testHost.home());
await p.evaluate(()=>{const data=JSON.parse(localStorage.getItem('mobTagLeagueProgressV2')),L=MobPartyLeague,league=data.league;let result;for(let i=0;i<3;i++){const d=L.next(league,()=>0),points=Object.fromEntries(league.active.flatMap(id=>league.teams.find(t=>t.id===id).members.map(p=>[p,100-Number(id.slice(1))*3])));result=L.submit(league,points,d)}league.pendingResult=result;window.beforeScores=JSON.stringify(league.scores);localStorage.setItem('mobTagLeagueProgressV2',JSON.stringify({...data,league}));testHost.home()});await p.locator('#partyLeague').tap();await p.locator('#leagueResume').tap();assert.match(await p.locator('.league-carryover').innerText(),/0pt/);assert.equal(await p.evaluate(()=>JSON.stringify(JSON.parse(localStorage.getItem('mobTagLeagueProgressV2')).league.scores)===beforeScores),true);
report.push({width,height,survival:'held finish/retry/home/league passed',pinball:'two drops/results passed',nativeLock:locks,representatives:'both buttons and images fit',carryover:'all eight plus wildcard zero, no extra award'});console.log('PASS fixes',width,height);await p.close();
}assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'fixes-browser.json'),JSON.stringify({report,errors},null,2));}finally{await b.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
