const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),output=fs.mkdtempSync(path.join(os.tmpdir(),'mob-new-leagues-'));
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,data)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(data);});});


(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{
for(const [width,height] of [[360,640],[390,600]]){const page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route(/^https?:\/\/(?!127\.0\.0\.1)/,r=>r.abort());await page.goto('http://127.0.0.1:'+server.address().port+'/index.html');
await page.click('#partyKingLeague');await page.selectOption('#variantCount','0');await page.click('#variantSelect');await page.click('#variantStart');
for(const division of ['PB2','Realize','Portal','DENDEN']){assert.match(await page.locator('.variant-league').innerText(),/高速処理/);await page.click('#variantNext');await page.locator('.result-announcement').waitFor();assert.match(await page.locator('.result-announcement').innerText(),/総合順位はこちら/);await page.locator('.result-announcement button').click();assert.match(await page.locator('.ranking-scope').innerText(),new RegExp(division));assert.match(await page.locator('.ranking-scope').innerText(),/自動集計/);assert.equal(await page.locator('.summary-qualified').count(),5);await page.click('#variantNext');}
page.once('dialog',d=>d.accept());await page.click('#homeBtn');await page.click('#partyLeague');await page.selectOption('#leagueCount','0');await page.click('#leagueSelect');await page.click('#leagueStart');await page.click('#leagueNext');await page.locator('.result-announcement button').click();assert.match(await page.locator('.tag-league').innerText(),/CPU自動集計 \/ 全10戦/);await page.click('#leagueNext');await page.click('#leagueNext');await page.locator('.result-announcement button').click();assert.match(await page.locator('.tag-league').innerText(),/CPU自動集計 \/ 全3戦/);page.once('dialog',d=>d.accept());await page.click('#homeBtn');await page.click('#partyCrew');await page.click('#variantSelect');await page.click('#partyConfirm');await page.click('#variantStart');for(let i=0;i<11;i++)await page.click('#variantNext');await page.locator('#introStart').waitFor();const frame=page.frameLocator('[data-live-preview]');await frame.locator('.reaction-stage').waitFor();await page.waitForTimeout(2200);
const bounds=await page.locator('#introStart,.game-preview,.illustrated-intro .panel').evaluateAll(nodes=>nodes.map(el=>el.getBoundingClientRect().toJSON()));assert.ok(bounds.every(r=>r.top>=0&&r.bottom<=height+1&&r.left>=0&&r.right<=width+1),JSON.stringify(bounds));await page.screenshot({path:path.join(output,'intro-'+width+'.png')});
await page.click('#introStart');await page.click('#readyBtn');await page.locator('.reaction-graffiti-btn-v186').click();await page.locator('#nextHuman').waitFor();await page.click('#nextHuman');await page.locator('.result-announcement').waitFor();assert.match(await page.locator('.result-announcement').innerText(),/GAME 1の結果はこちら/);await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>!!document.elementFromPoint(innerWidth/2,innerHeight/2)?.closest('.result-announcement')),true);await page.screenshot({path:path.join(output,'result-sting-'+width+'.png')});await page.locator('.result-announcement button').click();await page.click('#variantNext');assert.match(await page.locator('.result-announcement').innerText(),/総合順位はこちら/);await page.locator('.result-announcement button').click();assert.equal(await page.locator('.variant-row').count(),20);assert.deepEqual(errors,[]);await page.close();}
console.log('CPU-only four-league summaries, current-game live preview, human reaction scoring and result stings passed at both mobile widths.');console.log(output);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
