const artifactRoot=require('./visual-refresh-harness.cjs').output;for(const folder of ['qa','before','after'])require('fs').mkdirSync(require('path').join(artifactRoot,folder),{recursive:true});
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright'),{start}=require('./visual-refresh-harness.cjs'),catalog=require('./scenic-catalog.json');
const targets={slot:'.slot-machine',pk:'#pkField',cut:'#cutArea',errand:'.errand-shell',dontHitMob:'#moleBoard',mobStop:'#mobStopStage',overlap:'#overlapStage',shutter:'#shutterStage',darts:'.darts-main',parachute:'#paraStage',mobCount:'#countMobStage',brake:'#brakeStage',feint:'#feintStage',bomb:'.bomb-stage',overlapMaster:'#masterStage',jumpingMob:'#jumpupView',heroMaybe:'.hero-maybe-scene,#heroChoices',popularGame:'#popularView',planetEnergy:'#planetStage',painter:'#painterStage'};
const actual=process.argv.includes('--actual'),baseline=process.argv.includes('--baseline'),capture=process.argv.includes('--capture'),all=process.argv.includes('--all'),label=baseline?'before':actual?'actual':'after',only=process.env.SCENIC_ONLY,widthFilter=Number(process.env.SCENIC_WIDTH||0);
async function down(p,sel){await p.locator(sel).first().dispatchEvent('pointerdown',{pointerId:1,pointerType:'touch',isPrimary:true,button:0,buttons:1})}
async function begin(p,key){await p.evaluate(k=>testHost.select(k),key);await p.locator('#introStart').click();await p.locator('#readyBtn').click();if(await p.locator('.party-next-gate button').count())await p.locator('.party-next-gate button').click();await p.clock.runFor(1500);for(let i=0;i<10;i++){if(await p.locator('.party-next-gate button').count())await p.locator('.party-next-gate button').click();await p.clock.runFor(500);if(!await p.locator('.countdown-layer,.party-next-gate').count())break}await p.clock.runFor(50)}
async function drag(p,sel,dx,dy){const r=await p.locator(sel).boundingBox();let x=r.x+r.width*.45,y=r.y+r.height*.65;await p.mouse.move(x,y);await p.mouse.down();await p.mouse.move(x+dx,y+dy,{steps:6});await p.mouse.up()}
async function finish(p,key){
 if(key==='slot'){await p.locator('#slotMainBtn').dispatchEvent('click',{detail:0});await p.clock.runFor(300);for(const b of await p.locator('[data-slot-stop]').all())await b.click();await p.clock.runFor(11000)}
 else if(key==='pk'){for(let i=0;i<24&&!await p.locator('#soloReplay').count();i++){await drag(p,'#pkField',i%2?75:-75,0);await p.clock.runFor(700)}}
 else if(key==='cut'){for(let i=0;i<3;i++){await drag(p,'#cutArea',0,-85);await p.clock.runFor(600);await p.locator('#cutNextBtn').click();await p.clock.runFor(500)}}
 else if(key==='errand'){await down(p,'[data-item]');await p.clock.runFor(11000)}
 else if(key==='dontHitMob'){await down(p,'.mole-hole');await p.clock.runFor(11000)}
 else if(key==='mobStop'){await drag(p,'#mobStopMob',-70,0);await p.clock.runFor(6000)}
 else if(key==='overlap'){await down(p,'#overlapStage')}
 else if(key==='shutter'){for(let i=0;i<20&&await p.locator('#cameraBtn').isDisabled();i++)await p.clock.runFor(350);await down(p,'#cameraBtn');await p.clock.runFor(2000)}
 else if(key==='darts'){await down(p,'#dartStop');await p.clock.runFor(300);await down(p,'#dartStop');await p.clock.runFor(1000)}
 else if(key==='parachute'){await down(p,'#paraStage');await p.clock.runFor(14000)}
 else if(key==='mobCount'){await p.clock.runFor(3100);await down(p,'[data-count]')}
 else if(key==='brake'){await p.clock.runFor(1400);await down(p,'#brakeBtn');await p.clock.runFor(2500)}
 else if(key==='feint'){await down(p,'#feintStage')}
 else if(key==='bomb'){await p.clock.runFor(1200);await down(p,'#bombStop')}
 else if(key==='overlapMaster'){await down(p,'#masterStage')}
 else if(key==='jumpingMob'){await down(p,'#jumpRight');await down(p,'#jumpBtn');await p.clock.runFor(350);await p.locator('#jumpRight').dispatchEvent('pointercancel',{pointerId:1});await p.clock.runFor(11000)}
 else if(key==='heroMaybe'){for(let i=0;i<28;i++){if(await p.locator('[data-hero]:enabled').count())await down(p,'[data-hero]:enabled');await p.clock.runFor(500)}await p.locator('#heroSeeResult').click();await p.locator('#heroRecord').click()}
 else if(key==='popularGame'){await down(p,'#popularRight');await down(p,'#popularJump');await p.clock.runFor(350);await p.locator('#popularRight').dispatchEvent('pointercancel',{pointerId:1});await p.clock.runFor(11000)}
 else if(key==='planetEnergy'){for(let i=0;i<3;i++){await down(p,'#planetChargeTap');await p.clock.runFor(650)}await down(p,'#planetFire');await p.clock.runFor(16000)}
 else if(key==='painter'){const r=await p.locator('#painterSvg').boundingBox(),pts=[[70,205],[48,154],[43,62],[96,87],[150,72],[204,87],[257,62],[248,150],[230,205],[150,239],[70,205]];await p.mouse.move(r.x+pts[0][0]*r.width/300,r.y+pts[0][1]*r.height/300);await p.mouse.down();for(const [x,y] of pts.slice(1))await p.mouse.move(r.x+x*r.width/300,r.y+y*r.height/300,{steps:4});await p.mouse.up()}
 await p.clock.runFor(1600);assert.equal(await p.locator('#soloReplay').count(),1,key+' completes');await p.locator('#soloReplay').click();if(await p.locator('#introStart').count())await p.locator('#introStart').click();await p.locator('#readyBtn').click();if(await p.locator('.party-next-gate button').count())await p.locator('.party-next-gate button').click();await p.clock.runFor(key==='heroMaybe'?3800:2600);await p.locator('#homeBtn').click();await p.clock.runFor(300);assert.equal(await p.locator('#partySolo').count(),1,key+' returns home');
}
(async()=>{const {server,url}=await start(actual||baseline),b=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),rows=[];try{for(const [width,height] of (all?[[320,640],[390,600],[430,932],[1280,800]]:[[390,600]]).filter(([w])=>!widthFilter||w===widthFilter))for(const g of catalog.filter(g=>!only||only.split(',').includes(g.key))){const p=await b.newPage({viewport:{width,height},hasTouch:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**',r=>r.abort());await p.addInitScript(()=>{let seed=2929;window.randomCalls=0;Math.random=()=>{window.randomCalls++;return ((seed=(1664525*seed+1013904223)>>>0)/4294967296)}});await p.clock.install();await p.goto(url);await p.clock.pauseAt(new Date(await p.evaluate(()=>Date.now()+1000)));await begin(p,g.key);assert.ok(await p.locator(targets[g.key]).count(),g.key+' stage');if(!baseline){assert.equal(await p.locator('[data-scenic="'+g.key+'"]').count(),g.key==='heroMaybe'?2:1);assert.ok(await p.locator('[data-scenic="'+g.key+'"]').first().evaluate(e=>getComputedStyle(e).backgroundImage.startsWith('url(')))}
 const geometry=await p.locator(targets[g.key]+',#screen button,#painterSvg').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0&&getComputedStyle(e).visibility!=='hidden'&&(!e.closest('.cut-result-overlay,.hero-result-overlay')||e.closest('.show'))&&!e.closest('.hidden')}).map(e=>{const r=e.getBoundingClientRect();return{id:e.id,class:typeof e.className==='string'?e.className:'svg',x:r.x,y:r.y,w:r.width,h:r.height}}));const outside=geometry.filter(r=>r.x<-1||r.x+r.w>width+1||r.y<-1||r.y+r.h>height+1);assert.equal(outside.length,0,JSON.stringify({key:g.key,width,outside}));const randomCalls=await p.evaluate(()=>randomCalls);if(width===390)await p.screenshot({path:path.join(artifactRoot,label==='actual'?'qa':label,(actual?'actual-':'')+g.key+'.png'),animations:'disabled'});
 if(!capture)await finish(p,g.key);assert.deepEqual(errors,[],g.key);rows.push({no:g.no,key:g.key,width,height,geometry,randomCalls,completed:!capture,errors});fs.writeFileSync(path.join(artifactRoot,'qa/'+label+(all?'-all':'')+(widthFilter?'-'+widthFilter:'')+'.json'),JSON.stringify(rows,null,2));await p.close();console.log('PASS',label,width,g.no,g.key)} }finally{await b.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
