const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),output=fs.mkdtempSync(path.join(os.tmpdir(),'mob-season-'));
const hooks=`window.seasonHost={start(key){invalidateGameRun();state=freshState();state.freePlay=true;state.modeKey='solo';const i=GAMES.findIndex(g=>g.key===key);state.freeGameIndex=i;state.freePlayerId=PLAYERS[0].id;partyActivePlayer=PLAYERS[0];countdown=async()=>true;startSeasonGame(key,PLAYERS[0],0,beginGameRun(i));},records(){return state.records}};`;
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,data)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png'})[path.extname(file)]||'application/octet-stream');if(path.basename(file)==='game.js')data=data.toString().replace(/if\(previewKey\)startLivePreview\(\);else renderHome\(\);/,hooks+'renderHome();');if(path.basename(file)==='party-season-games.js')data=data.toString().replace('const render=dt=>',`root.seasonProbe=()=>({time,phase,level,power,runner,gauge:gaugeAt(time-phaseTime),mode,px,py,ended,score,spawned,caught,missed,bananas,boat,presents:presents.map(g=>({...g,...giftPos(g)}))});const render=dt=>`);res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{
  for(const [width,height] of [[360,640],[390,600]]){
    const page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route(/^https?:\/\/(?!127\.0\.0\.1)/,r=>r.abort());await page.goto('http://127.0.0.1:'+server.address().port+'/index.html');if(process.env.CATALOG_ONLY){for(const title of ['そんなバナナ','そり立つ壁','サンタクロース']){await page.click('#partySolo');await page.click('#partyConfirm');await page.click('#partySingle');assert.equal(await page.locator('[data-game]').count(),138);await page.fill('#partySearch',title);await page.locator('[data-game]').click();assert.ok(await page.locator('[data-live-preview]').count());assert.ok(!(await page.locator('#screen').innerText()).includes('SASUKE'));await page.click('#introStart');await page.click('#readyBtn');await page.locator('.season-shell canvas').waitFor();await page.click('#homeBtn');}assert.deepEqual(errors,[]);await page.close();continue;}await page.clock.install();
    const start=async key=>{await page.evaluate(k=>window.seasonHost.start(k),key);await page.clock.runFor(16);};
    const bounds=async()=>{const rs=await page.locator('.season-world,.season-actions').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().toJSON()));assert.ok(rs.every(r=>r.width>0&&r.height>=44&&r.x>=0&&r.right<=width&&r.y>=0&&r.bottom<=height),JSON.stringify(rs));};
    await start('bananaBoatMob');await bounds();
    for(let i=0;i<450;i++){const s=await page.evaluate(()=>window.seasonProbe());if(s.ended)break;await page.locator('canvas').evaluate(c=>{const s=window.seasonProbe(),b=s.bananas.filter(b=>!b.dead).sort((a,b)=>b.y-a.y)[0];if(!b)return;const r=c.getBoundingClientRect();c.dispatchEvent(new PointerEvent('pointerdown',{pointerId:1,clientX:r.x+b.x*r.width,clientY:r.y+r.height*.8}));});await page.clock.runFor(50);if(i===90)await page.screenshot({path:path.join(output,`banana-${width}.png`)});}
    let s=await page.evaluate(()=>window.seasonProbe());assert.equal(s.spawned,30);assert.equal(s.caught+s.missed,30);assert.ok(s.score>=96,s.score);await page.clock.runFor(900);await page.locator('#soloReplay').waitFor();
    await start('warpedWallMob');await bounds();
    for(let i=0;i<1600;i++){s=await page.evaluate(()=>window.seasonProbe());if(s.ended)break;if(s.phase==='gauge'&&Math.abs(s.gauge-.5)<.025||s.phase==='run'&&Math.abs(s.runner-.62)<.007)await page.locator('#seasonAction').dispatchEvent('click');await page.clock.runFor(16);if(i===100)await page.screenshot({path:path.join(output,`wall-${width}.png`)});}
    s=await page.evaluate(()=>window.seasonProbe());assert.equal(s.level,3);assert.equal(s.ended,true);assert.ok(s.score>=95,s.score);await page.clock.runFor(900);await page.locator('#soloReplay').waitFor();
    await start('santaClausMob');await bounds();const box=await page.locator('canvas').boundingBox();assert.ok(Math.abs(box.width-box.height)<=1,JSON.stringify(box));
    await page.locator('canvas').evaluate(c=>{const g=window.seasonProbe().presents[0],r=c.getBoundingClientRect();c.dispatchEvent(new PointerEvent('pointerdown',{clientX:r.x+g.x*r.width,clientY:r.y+g.y*r.height}));});
    await page.clock.runFor(500);s=await page.evaluate(()=>window.seasonProbe());assert.equal(s.mode,'carry');assert.equal(s.score,0);
    for(let i=0;i<17;i++){await page.locator(`[data-hand="${i%2}"]`).dispatchEvent('pointerdown');await page.clock.runFor(32);}s=await page.evaluate(()=>window.seasonProbe());assert.equal(s.score,25);await page.screenshot({path:path.join(output,`santa-${width}.png`)});await page.clock.runFor(12000);s=await page.evaluate(()=>window.seasonProbe());assert.equal(s.ended,true);assert.equal(s.score,25);await page.locator('#soloReplay').waitFor();
    assert.deepEqual(errors,[]);await page.close();
  }
  console.log('Three games completed with scoring, controls and mobile layout verified.');console.log(output);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
