const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),output=fs.mkdtempSync(path.join(os.tmpdir(),'mob-balance-'));
const hooks=`window.balanceTest={start(key){invalidateGameRun();state=freshState();state.freePlay=true;state.modeKey='solo';const i=GAMES.findIndex(g=>g.key===key);state.freeGameIndex=i;state.freePlayerId=PLAYERS[0].id;partyActivePlayer=PLAYERS[0];const id=beginGameRun(i);countdown=async()=>true;const name='start'+key[0].toUpperCase()+key.slice(1);eval(name)(PLAYERS[0],0,id);},records(){return state.records}};`;
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,data)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png'})[path.extname(file)]||'application/octet-stream');if(path.basename(file)==='game.js')data=data.toString().replace(/if\(previewKey\)startLivePreview\(\);else renderHome\(\);/,hooks+'renderHome();');if(path.basename(file)==='game.js'){let text=data.toString(),a=text.indexOf('async function startSkiJump3DMob('),b=text.indexOf('async function startCraneGame3DMob(',a);let ski=text.slice(a,b).replace('function loop(now){','window.skiProbe=()=>({active,phase,z,y,airTime,tilt,takeErr,scoreFinal});function loop(now){');data=text.slice(0,a)+ski+text.slice(b);}res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{
for(const [width,height] of [[360,640],[390,600]]){const page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/three.min.js',r=>r.fulfill({path:path.join(os.tmpdir(),'mob-three-r159.js'),contentType:'application/javascript'}));await page.goto('http://127.0.0.1:'+server.address().port+'/index.html');await page.clock.install({time:new Date('2026-10-02T00:00:00Z')});await page.clock.pauseAt(new Date('2026-10-02T00:00:01Z'));
const start=async key=>{await page.evaluate(k=>window.balanceTest.start(k),key);await page.clock.runFor(32);};
await start('skiJump3DMob');for(let i=0;i<70;i++){const s=await page.evaluate(()=>window.skiProbe());if(s.z<=-7.20){await page.locator('#sjJump').dispatchEvent('pointerdown');break;}await page.clock.runFor(40);}
assert.equal((await page.evaluate(()=>window.skiProbe())).phase,'air');await page.clock.runFor(1800);let s=await page.evaluate(()=>window.skiProbe());assert.equal(s.phase,'air');assert.ok(s.y>8,s.y);
const rs=await page.locator('#sjStage,.mob3d-controls-v237').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().toJSON()));assert.ok(rs.every(r=>r.top>=0&&r.bottom<=height&&r.left>=0&&r.right<=width),JSON.stringify(rs));await page.screenshot({path:path.join(output,'ski-flight-'+width+'.png')});
await page.clock.runFor(4500);s=await page.evaluate(()=>window.skiProbe());assert.equal(s.phase,'land');assert.ok(s.airTime>=4.5&&s.airTime<6,s.airTime);assert.ok(s.scoreFinal>=50&&s.scoreFinal<=100,s.scoreFinal);
await page.clock.runFor(3000);await page.locator('#soloReplay').waitFor();
await start('tamaireMob');const xs=[];for(let i=0;i<20;i++){xs.push(await page.locator('#tamaBasket170').evaluate(e=>e.getBoundingClientRect().x));await page.clock.runFor(100);}assert.ok(Math.max(...xs)-Math.min(...xs)>55);const basketRects=await page.locator('.tama-basket-v170').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().toJSON()));assert.ok(basketRects.every(r=>r.left>=0&&r.right<=width));assert.deepEqual(errors,[]);await page.close();}
console.log('3D flight duration, landing scores, basket movement and mobile controls passed.');console.log(output);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});