const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),output=fs.mkdtempSync(path.join(os.tmpdir(),'mob-new-leagues-'));
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,data)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(data);});});

(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{
for(const [width,height] of [[360,640],[390,600]]){const page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port+'/tests/tag-edit-preview.html');await page.selectOption('#leagueCount','2');await page.click('#leagueSelect');await page.click('#leagueStart');
const until=async text=>{for(let i=0;i<180;i++){if((await page.locator('#screen').innerText()).includes(text))return;await page.locator('#leagueNext').click();}throw Error('Not reached '+text);};
const bounds=async selector=>{const rs=await page.locator(selector).evaluateAll(es=>es.map(e=>e.getBoundingClientRect().toJSON()));assert.ok(rs.every(r=>r.top>=0&&r.bottom<=height&&r.left>=0&&r.right<=width),JSON.stringify(rs));};
await until('ルーレットを回す');await bounds('.roulette-options,#leagueNext,.roulette-stage');await page.waitForTimeout(550);const wheel=await page.locator('#leagueWheel').boundingBox(),options=await page.locator('.roulette-options').boundingBox();assert.ok(wheel.y+wheel.height<=options.y,JSON.stringify({wheel,options}));await page.screenshot({path:path.join(output,'roulette-'+width+'.png')});await page.click('#leagueNext');await page.locator('#leagueNext').filter({hasText:'このゲームで勝負'}).waitFor();assert.equal(await page.locator('.roulette-options .selected').count(),1);const picked=(await page.locator('.roulette-options .selected').innerText()).slice(1).trim();await page.click('#leagueNext');assert.ok((await page.locator('#screen').innerText()).includes(picked));
await until('GAME 6 · 種目を選ぼう');await page.click('#leagueChoice0');assert.equal(await page.locator('#leagueChoice0').isDisabled(),true);await page.click('#leagueChoice1');await until('GAME 7 · 種目を選ぼう');assert.equal(await page.locator('.league-choice-games button').count(),4);await bounds('.league-choice-games button');await page.screenshot({path:path.join(output,'four-choices-'+width+'.png')});await page.click('#leagueChoice3');
await until('GAME 8 · 種目を選ぼう');await bounds('.league-choice-games button');assert.match(await page.locator('.league-choice-games').innerText(),/サンタクロース/);await page.click('#leagueChoice0');assert.equal(await page.locator('#leagueChoice0').isDisabled(),true);await page.click('#leagueChoice1');await until('今回のチーム順位');const eighth=await page.evaluate(()=>played.filter(r=>r.round===8&&r.phase==='qualifier'));assert.equal(eighth.length,40);assert.deepEqual(eighth.filter(r=>r.ids.includes('p1')||r.ids.includes('p2')).map(r=>r.key),['warpedWallMob','santaClausMob']);assert.deepEqual(errors,[]);await page.close();}
console.log('Round 4 roulette and round 7/8 choices passed on both mobile sizes.');console.log(output);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});