const artifactDir=require('./visual-refresh-harness.cjs').output;
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright'),{start,ready}=require('./visual-refresh-harness.cjs');
(async()=>{const {server,url}=await start(),b=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),report=[];try{for(const [width,height] of [[320,640],[390,600],[430,932]]){const p=await b.newPage({viewport:{width,height},hasTouch:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**',r=>r.abort());await p.clock.install();await p.goto(url);await p.locator('#partySolo').click();await p.locator('#partyConfirm').click();const actor=await p.locator('.party-team img').getAttribute('src');await p.locator('#partySingle').click();await p.waitForTimeout(100);assert.equal(await p.locator('[data-game]').count(),147);await p.waitForFunction(()=>!!document.querySelector('[data-cover][data-ready]'));await p.screenshot({path:path.join(artifactDir,'library-'+width+'.png'),animations:'disabled'});
const bad=await p.locator('.party-catalog input,.party-catalog button').evaluateAll(es=>es.filter(e=>e.getClientRects().length&&!e.closest('.party-genres')).filter(e=>{const r=e.getBoundingClientRect();return r.left<0||r.right>innerWidth+1||r.width<43||r.height<43}).map(e=>e.id||e.className));assert.deepEqual(bad,[],width+' catalogue bounds');
await p.locator('#partySearch').fill('反射神経');assert.equal(await p.locator('[data-game]').count(),1);const id=await p.locator('[data-game]').getAttribute('data-game');await p.locator('[data-game]').click();await p.waitForFunction(()=>document.querySelector('[data-preview-ready=true]'));assert.equal(await p.locator('.intro-deck').count(),1);const box=await p.locator('.intro-deck').boundingBox();assert.ok(Math.abs(box.width-box.height)<1);const title=await p.locator('.game-head h2').textContent();assert.match(title,/反射神経/);
for(let i=0;i<await p.locator('.intro-tabs button').count();i++){await p.locator('.intro-tabs button').nth(i).click();const rects=await p.locator('.intro-deck,.intro-tabs,#introStart,#introBack').evaluateAll(es=>es.filter(e=>e.getClientRects().length).map(e=>e.getBoundingClientRect().toJSON()));assert.ok(rects.every(r=>r.left>=-1&&r.right<=width+1&&r.top>=0&&r.bottom<=height-5),JSON.stringify({width,rects}));}await p.locator('#introTab1').click();await p.screenshot({path:path.join(artifactDir,'intro-rules-'+width+'.png'),animations:'disabled'});await p.locator('#introTab0').click();await p.screenshot({path:path.join(artifactDir,'intro-'+width+'.png'),animations:'disabled'});
await p.locator('#introBack').click();assert.equal(await p.locator('#partySearch').inputValue(),'反射神経');assert.equal(await p.locator('[data-game]').getAttribute('data-game'),id);assert.equal(await p.locator('#screen').evaluate(e=>e.classList.contains('illustrated-intro')),false);await p.locator('[data-game]').click();await p.clock.pauseAt(new Date(Date.now()+500));await ready(p);await p.clock.runFor(2400);await p.locator('.reaction-graffiti-btn-v186').dispatchEvent('pointerdown');await p.clock.runFor(1400);assert.equal(await p.locator('#soloReplay').count(),1);await p.locator('#soloHome').click();assert.equal(await p.locator('#partySolo').count(),1);
await p.locator('#partySolo').click();await p.locator('#partyConfirm').click();await p.locator('#partySingle').click();await p.clock.runFor(50);await p.locator('#partySearch').fill('ギャラクシー');await p.locator('[data-game]').click();await p.clock.runFor(100);await ready(p);await p.clock.fastForward(14000);assert.equal(await p.locator('#soloReplay').count(),1);await p.locator('#soloHome').click();
// Search composition, genre, empty state and Cup queue keep existing game-index semantics.
await p.locator('#partySolo').click();await p.locator('#partyConfirm').click();await p.locator('#partySingle').click();await p.clock.runFor(50);await p.locator('[data-genre="頭脳・記憶"]').click();assert.ok(await p.locator('[data-game]').count()>0);await p.locator('#partySearch').fill('見つからない文字列');assert.equal(await p.locator('[data-game]').count(),0);await p.locator('#partySearchClear').click();assert.ok(await p.locator('[data-game]').count()>0);await p.locator('#partyBack').click();assert.equal(await p.locator('.party-team img').getAttribute('src'),actor);await p.locator('#partyCup').click();await p.locator('[data-rounds="10"]').click();await p.clock.runFor(50);const first=p.locator('[data-game]').first();await first.click();assert.equal(await first.getAttribute('aria-pressed'),'true');await first.click();assert.match(await first.locator('.catalog-picked').textContent(),/2回/);await p.locator('#partyUndo').click();assert.match(await first.locator('.catalog-picked').textContent(),/1回/);await p.locator('#partyRandomFill').click();assert.equal(await p.locator('#partyLaunch').isDisabled(),false);assert.match(await p.locator('#partyLaunch').textContent(),/10 \/ 10/);await p.locator('#partyLaunch').click();assert.equal(await p.locator('#partyGames').count(),0);p.once('dialog',d=>d.accept());await p.locator('#homeBtn').click();assert.equal(await p.locator('#partySolo').count(),1);
assert.deepEqual(errors,[]);report.push({width,height,square:box.width,library:147,legacyEnd:true,newEnd:true,searchBack:true,cupQueue:true,errors});await p.close();console.log('UI PASS',width)}fs.writeFileSync(path.join(artifactDir,'ui.json'),JSON.stringify(report,null,2));}finally{await b.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
