const artifactDir=require('./visual-refresh-harness.cjs').output;
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright'),{start,ready}=require('./visual-refresh-harness.cjs');
(async()=>{const actual=false,{server,url}=await start(actual),b=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),report=[],errors=[];try{for(const [width,height] of [[320,640],[390,600],[430,932]]){const p=await b.newPage({viewport:{width,height},hasTouch:true});p.on('pageerror',e=>errors.push(e.message));await p.route('https://**',r=>r.abort());await p.clock.install();await p.goto(url);await p.clock.pauseAt(new Date(Date.now()+500));
async function shot(key){await p.screenshot({path:path.join(artifactDir,`${key}-${width}.png`)})}
async function visible(sel){for(const r of await p.locator(sel).evaluateAll(es=>es.map(e=>{let r=e.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height}})))assert(r.x>=-1&&r.y>=-1&&r.x+r.w<=width+1&&r.y+r.h<=height+1,sel+JSON.stringify(r))}
async function catcher(toko){const prefix=toko?'ttk':'catch',stop=toko?'#ttkStop188':'#catchStop191',drop=toko?'#ttkDrop188':'#catchDrop191',guide=toko?'#ttkCall188':'#catchGuide191';for(let i=0;i<160&&!await p.locator('#soloReplay').count();i++){if(await p.locator(stop).count()&&!await p.locator(stop).isDisabled()){const label=await p.locator(guide).innerText();if(/アーム幅|STOP|降下中/.test(label))await p.locator(stop).dispatchEvent('pointerdown',{pointerId:1})}if(await p.locator(drop).count()&&!await p.locator(drop).isDisabled())await p.locator(drop).dispatchEvent('pointerdown',{pointerId:1});await p.clock.runFor(250)}assert.equal(await p.locator('#soloReplay').count(),1,prefix+' finish')}
for(const key of ['reaction','memory','puzzle','launch','stack','breakdance','factory','catcher','tidy','ski']){
 await ready(p,key);await shot(key);assert.equal(await p.locator('#screen').getAttribute('data-classic'),key);
 if(key==='reaction'){await p.clock.runFor(2200);await p.locator('.reaction-graffiti-btn-v186').dispatchEvent('pointerdown')}
 else if(key==='memory'){await p.clock.runFor(11000);await p.locator('.memory-tile').first().dispatchEvent('pointerdown');await p.clock.runFor(1000);if(!await p.locator('#soloReplay').count()){await p.locator('.memory-tile').first().dispatchEvent('pointerdown');await p.clock.runFor(1000)}}
 else if(key==='puzzle'){for(let n=1;n<=12;n++)await p.locator(`[data-num="${n}"]`).dispatchEvent('pointerdown');await p.clock.runFor(500)}
 else if(key==='launch'){await p.locator('#linearGauge').dispatchEvent('pointerdown');await p.locator('#circleGauge').dispatchEvent('pointerdown');await p.clock.runFor(12000)}
 else if(key==='catcher')await catcher(false);
 else await p.clock.fastForward(20000);
 if(!await p.locator('#soloReplay').count())await p.clock.runFor(3000);if(key==='breakdance'){await p.locator('#worldRankingBtn').click();await p.locator('#worldResultBtn').click()}assert.equal(await p.locator('#soloReplay').count(),1,key+' completion');await p.locator('#soloReplay').click();await ready(p);await p.locator('#homeBtn').click();await p.clock.fastForward(20000);assert.equal(await p.locator('#soloReplay').count(),0,key+' stale result');report.push({width,key,checked:'start, finish, result, replay, home'});console.log('PASS',width,key)
}await p.close()}assert.deepEqual(errors,[]);fs.writeFileSync(path.join(artifactDir,actual?'classic-bugs-actual.json':'classic-bugs-staged.json'),JSON.stringify({report,errors},null,2));console.log('PASS classic + bugs',report.length)}finally{await b.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
